### ISSUE TITLE
Qt 5.5.1: undocked windows can't be resized

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1010]
This is because due to an issue in Qt 5.5.1 ([QTBUG-46882](
https://bugreports.qt.io/browse/QTBUG-46882)) which is fixed by https://codereview.qt-project.org/#/c/125923/.

**Comment by agarny** [comment]
Argh, I hadn't noticed it, but I can indeed confirm the problem on OS X.

Now, the real problem is that although it has been officially fixed on 22 September, it didn't make it into Qt 5.5.1, which was shipped on 15 October (!!). Then, with Qt 5.6 LTS having been released and Qt 5.7 having just been released too, I am somewhat concerned that we will never see a Qt 5.5.2, which would be annoying since we can't currently upgrade to Qt 5.6 LTS or Qt 5.7 (Qt WebEngine is not yet good enough for all we need). Ok, I am somehow going to check with the Qt guys to find out about a possible Qt 5.5.2... :s

**Comment by agarny** [comment]
FWIW, a comment was posted on both [QTBUG-46882](https://bugreports.qt.io/browse/QTBUG-46882) and the [Qt forum](https://forum.qt.io/topic/68430/is-there-ever-going-to-be-a-qt-5-5-2-release).

**Comment by agarny** [comment]
Unsurprisingly, it looks like there might never be a 5.5.2 version of Qt. Yet, to be able to resize a floating window is such a basic feature that we can't ignore it.

After some more thinking and digging around, I feel like switching to Qt 5.6.1 (as opposed to Qt 5.7 since the former is an LTS version) is the way to go. Now, since we can't currently use Qt WebEngine (see issue #908), this means that we will need to build Qt WebKit ourselves.

On the [Qt forum](https://forum.qt.io/topic/68430/is-there-ever-going-to-be-a-qt-5-5-2-release), I was told about [Qt WebKit Reloaded](https://github.com/annulen/webkit/wiki). Ideally, this is what we would be using, but it's not yet ready for consumption.

So, instead, my plan is to build the Qt WebKit version that we know works with Qt 5.6.1 (see [here](http://download.qt.io/community_releases/5.6/5.6.1/)). There are some up-to-date information on how to build it on [Windows](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows
), [Linux](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux) and [Mac](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-OS-X), so it ought to be fine. (As it happens, earlier, I was able to build Qt WebKit on Linux and Mac just fine.)

**Comment by agarny** [comment]
Closing this issue since it ought to be addressed by upgrading to Qt 5.6.1 LTS + Qt WebKit (see issue #1015).

**Comment by dbrnz** [comment]
FWIW this issue should remain open until #1015 is completed, as being unable to resize undocked windows is an issue for anyone who uses a Qt5.5 version of OpenCOR.

**Comment by agarny** [comment]
> FWIW this issue should remain open until #1015 is completed, as being unable to resize undocked windows is an issue for anyone who uses a Qt5.5 version of OpenCOR.

Fair enough.

**Comment by agarny** [comment]
Closing as a result of https://github.com/opencor/opencor/commit/e67124004a014ab3a8355a507bf84696d69ec624.
