### ISSUE TITLE
problem with variables "not existing"

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1029]
Possibly already fixed, but in the July 1 2016 snapshot if you open the model https://models.physiomeproject.org/workspace/242/rawfile/1e148670c368f49ba887341e10609a00640e7ac6/experiments/single-stimulus.xml you can simulate it, but not plot against the variable of integration.

This is probably due to `time` being defined elsewhere and just declared in the top-level model for the purpose of plotting.

**Comment by agarny** [comment]
Actually, now, you don't need `time` to be declared anywhere in the main CellML file to be able to run a CellML 1.1 file (see issue #995). However, for `time` to be listed in the `Parameters` panel, it needs to have its 'source variable' in a component in the main CellML file (as is the case with `Vm` and `stimTime`).

By the way, I can see that you are using `model` as one of a component name. As you may expect, when using the `CellML Text` view, you cannot use any of the language keywords as the name of a model, component, variable, etc.

**Comment by nickerso** [comment]
Yep, I can definitely run the simulation - I just can't plot anything against `time`. So is that a bug or a feature? :)

**Comment by agarny** [comment]
It is 'feature'.

Indeed, the model contains a VOI and although it's originally declared in an imported component, it's still declared, hence OpenCOR considers the model valid (as it should indeed!). However, because the VOI is not declared in the main CellML file, it's not listed in the `Parameters` panel, and therefore cannot be used for the X and/or Y axis of a graph.

Now, there is a bug of sorts in the sense that we shouldn't be able to plot a parameter against the `Variable of Integration`. So, that menu item should be removed indeed (see issue #1030).

**Comment by nickerso** [comment]
sorted. So I'll close this one...
