### ISSUE TITLE
General: the desktop icon doesn't show on Ubuntu

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1147]
It's actually an unimportant issue, but Ubuntu doesn't show the OpenCOR icon in the desktop and only uses the default system icon. I thought it would be nice if it can be fixed.

**Comment by agarny** [comment]
Hmm, good point @ssafaei! It's actually a strange one because I have some code to set the desktop icon and I haven't changed it in years. Yet, it has worked in the past and not in other occasions. Right now, testing OpenCOR on my development Ubuntu 14.04 LTS virtual machine, I can see that it's not working. Ok, I am going to look into it.

P.S.: never say something is not important or we might take your word for it and never implement/fix it... :)

**Comment by ssafaei** [comment]
I tried the latest snapshot on ubuntu 16.10 and 14.04, it still doesn't show the desktop icon.

**Comment by ssafaei** [comment]
![screenshot from 2016-11-18 11-18-55](https://cloud.githubusercontent.com/assets/880165/20410679/2ba0ee72-ad83-11e6-86c0-77609175467f.png)

**Comment by agarny** [comment]
Argh, really sorry @ssafaei!

I have identified the problem and I am going to fix it straightaway.

**Comment by agarny** [comment]
@ssafaei: please re-download the 2016-11-17 snapshot. It should now be fine (fingers crossed!).

**Comment by agarny** [comment]
@ssafaei: by the way, I noticed that on 14.04 LTS, it may not work the first time you launch OpenCOR. However, it should be fine the second time round. (16.04 LTS doesn't seem to be affected by this.)

**Comment by ssafaei** [comment]
it works perfectly now! thanks :)

**Comment by agarny** [comment]
Phew! :)
