### ISSUE TITLE
CLI: a plugin's initialisation and finalisation code isn't called when run from the CLI

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1173]
Is this a design feature or an oversight??

**Comment by agarny** [comment]
Are you talking about the `initializePlugin()` and `finalizePlugin()` from the `Plugin` interface? If so, then this is some kind of an oversight on my part. Some kind because, as you know, we have mainly concentrated on the GUI side of things until now, and the few CLI-capable plugins that we have don't take advantage of those methods. Anyway, thanks a lot for bringing it up!

Now, if we look at the `Plugin` interface, we have the following methods:

```
virtual bool definesPluginInterfaces() PURE;
virtual bool pluginInterfacesOk(const QString &pFileName,
                                QObject *pInstance) PURE;

virtual void initializePlugin() PURE;
virtual void finalizePlugin() PURE;

virtual void pluginsInitialized(const Plugins &pLoadedPlugins) PURE;

virtual void loadSettings(QSettings *pSettings) PURE;
virtual void saveSettings(QSettings *pSettings) const PURE;

virtual void handleUrl(const QUrl &pUrl) PURE;
```

Both `definesPluginInterfaces()` and `pluginInterfacesOk()` are used when trying to load a plugin.

`handleUrl()` is used to interact with OpenCOR from a web browser, so this shouldn't be of any use to the CLI version of OpenCOR.

Now, when it comes to `initializePlugin()`, `finalizePlugin()`, `pluginsInitialized()`, `loadSettings()` and `saveSettings()`, they all ought to be used in the CLI version of OpenCOR and I agree that they are not being used at the moment.

Ok, I am going to look into it ASAP.

**Comment by dbrnz** [comment]
Thanks! :-)
