### ISSUE TITLE
File Handling interface: remove `isIndirectRemoteFile()` since it's not being used anymore

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1267]
Spotted while working on #1266. OpenCOR builds with the function (in `filehandlinginterface.inl`), along with all instantiations, commented out; @agarny is it safe to remove it??

**Comment by agarny** [comment]
Well spotted, I now remember that I managed to find a way to go around the need for `isIndirectRemoteFile()`, but then clearly forgot to remove it.

FWIW, the original need was in case of a local SED-ML file that was referencing a remote CellML file (hence `isIndirectRemoteFile()` indeed), in which case we wanted to show the busy widget when opening such a local SED-ML file. I can't recall how I got around that specific case, but I have just tried it and it's working as expected, so it's all safe to remove `isIndirectRemoteFile()`. In fact, I am going to do it now since it requires cleaning up some other code as well.
