### ISSUE TITLE
Python: wrap Solver objects

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1270]
This is so that properties of a solver can be set from Python.

**Comment by agarny** [comment]
From what I understand, a Python wrapper is clearly needed, but let us not forget that OpenCOR is a plugin-based environment.

I mean that, looking at your commit 0f704cd, it looks like you have a `PythonWrapper` plugin that wraps various things from different OpenCOR plugins. Is that the case? If so, then I am not sure this is the way we should be doing since we may end up with your `PythonWrapper` plugin having dependencies on pretty much all of the OpenCOR plugins, thus making our plugin-based approach rather useless.

I clearly haven't put much thought into this, but wouldn't it be possible to have those Python wrappers directly in the plugins for which we would like to have Python wrappers? Maybe this could even be done using some kind of an interface, as we have done for say the `Solver` interface? Maybe something to discuss face to face...

**Comment by dbrnz** [comment]
I considered having wrapper code in with a plugin but then decided to go with a separate PythonWrapper plugin to minimise code changes to wrapped classes. Having wrappers directly in plugins is the cleaner way to do things and I've created issue #1275 for this.

**Comment by agarny** [comment]
Great. Probably need to close this issue then?

**Comment by dbrnz** [comment]
Closing as now part of #1275.
