### ISSUE TITLE
Python: use an interface for wrapping classes

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1275]
This will replace the PythonWrapper plugin and keep wrapping code with the appropriate class.

**Comment by dbrnz** [comment]
Completed and ready for merge from pythonplugin branch.

**Comment by agarny** [comment]
Sorry @dbrnz, are you asking me to merge your [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch into our [master](https://github.com/opencor/opencor) branch?

The reason I am asking is that I have just had a quick look at the [diff](https://github.com/opencor/opencor/compare/master...dbrnz:pythonplugin) between your [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch and our [master](https://github.com/opencor/opencor) branch, and there are a few things that puzzle me, e.g.:
 - It cannot currently be automatically merged.
 - Some files use the Apache 2.0 license rather than the GPLv3 one (e.g. [`src/plugins/eventloopinterface.cpp`](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/eventloopinterface.cpp)).
 - Why is there a Python wrapper for our `SimulationExperiment` view? Is it only temporary, i.e. until we properly decouple a simulation from our `SimulationExperiment` view? Also, things are bound to change quite a bit as a result of my current work on issue #217.
 - Why the [`src/plugins/thirdParty/OpenSSL/.gitignore`](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/thirdParty/OpenSSL/.gitignore) and [`src/plugins/thirdParty/OpenSSL/README.rst`](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/thirdParty/OpenSSL/README.rst) files?
 - From [`src/plugins/thirdParty/PythonPackages/README.rst`](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/thirdParty/PythonPackages/README.rst), am I to understand that we will simply not be able to build a Windows debug version of OpenCOR anymore?
 - Why [`src/plugins/thirdParty/PythonQtAPI/qmake`](https://github.com/dbrnz/opencor/tree/pythonplugin/src/plugins/thirdParty/PythonQtAPI/qmake) folder? Why is it not part 
 - We don't need to include `ExternalProject` anymore and we now have a 'global' variable for `qmake` (see [here](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/thirdParty/PythonQtAPI/CMakeLists.txt#L83) and [here](https://github.com/opencor/opencor/blob/e5f4dfa3a0da8c20bdaa2e39e131cb27bca8a1b6/CMakeLists.txt#L112)).

**Comment by dbrnz** [comment]
It's not my intent that the pythonplugin branch be merged at this stage. It represents the current state of Python in OpenCOR and is very much WIP, especially given the work on separating out a simulation from its view and on multiple simulation runs.

You comments though are useful pointers to some tidying up, thanks. (And I thought I had changed all licenses...). A couple of responses:

> * From src/plugins/thirdParty/PythonPackages/README.rst, am I to understand that we will simply not be able to build a Windows debug version of OpenCOR anymore?

Correct. Even building a debug version of the Python library under Windows is difficult. My understanding is that one cannot mix debug and non-debug DLLs in a Windows application because of differences in C run-time library calling conventions (and there's enough advice on StackOverflow against doing so). Hmm, we don't use debug versions of Qt's DLLs, so supposedly they can be mixed. What is you experience of mixing debug and release DLLs under Windows??

> * Why src/plugins/thirdParty/PythonQtAPI/qmake folder? Why is it not part

It contains files that are configured by CMake prior to running qmake by ExternalProject_Add. Your following question though is truncated.

**Comment by agarny** [comment]
> It's not my intent that the pythonplugin branch be merged at this stage. It represents the current state of Python in OpenCOR and is very much WIP, especially given the work on separating out a simulation from its view and on multiple simulation runs.

Ok, that's what I thought then. I just wanted to be sure since you closed this issue and, for me, it would normally mean that work on the closed issue has been or is to be merged in the `master` branch.

> > * From src/plugins/thirdParty/PythonPackages/README.rst, am I to understand that we will simply not be able to build a Windows debug version of OpenCOR anymore?

> Correct. Even building a debug version of the Python library under Windows is difficult. My understanding is that one cannot mix debug and non-debug DLLs in a Windows application because of differences in C run-time library calling conventions (and there's enough advice on StackOverflow against doing so).

My understanding is also that release and debug DLLs cannot be mixed. I certainly remember having problems (in OpenCOR, very early on) when trying to do so.

> Hmm, we don't use debug versions of Qt's DLLs, so supposedly they can be mixed. What is you experience of mixing debug and release DLLs under Windows??

How do you mean? We do use debug versions of Qt's DLLs when building a debug version of OpenCOR:

![image](https://user-images.githubusercontent.com/602265/27956952-5d531676-631c-11e7-9e37-2c46491de392.png)

Just to make sure, I replaced the debug version of Qt's DLLs with their release counterpart (and made sure that Qt is not in the `PATH`) and, unsurprisingly, Windows complained about a (debug) Qt DLL being missing. When it comes to building OpenCOR, we don't seem to be able to  specify whether we want to link against the release or debug version of OpenCOR (see [here](https://github.com/opencor/opencor/blob/931bbaa6e64ab8ef37aa94545c474e631696bd61/CMakeLists.txt#L906)). So, I would say that there is no way around it.

> > * Why src/plugins/thirdParty/PythonQtAPI/qmake folder? Why is it not part

> It contains files that are configured by CMake prior to running qmake by ExternalProject_Add.

Can't this be done as part of `ExternalProject_Add`'s `CONFIGURE_COMMAND` argument?

> Your following question though is truncated. 

Oops, my bad. I meant to ask: why is it not part of [`https://github.com/opencor/pythonqt`](https://github.com/opencor/pythonqt)?

Otherwise, shouldn't the `PythonQtAPI` plugin be under [`src/plugins/api`](https://github.com/opencor/opencor/tree/master/src/plugins/api)?
