### ISSUE TITLE
Macos: missing close tab icon

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1456]
The tab bar drawing code for macos was reworked as part of upgrading to Qt 5.9.x LTS (#1311). However the close tab icon (X) no longer shows on tab labels -- the screenshoot is with the cursor hovering over where the icon should be.

![screen shot 2017-11-02 at 9 17 30 am](https://user-images.githubusercontent.com/239220/32295947-a63819b8-bf42-11e7-9eeb-c95e5b3730b2.png)

**Comment by agarny** [comment]
You got me worried for a second since I thought I had checked all possible combinations. So, I just tried the latest (2017-10-23) snapshot on my MBP with macOS 10.13 (High Sierra) on it, and as far as I can tell it's all working fine:

![image3](https://user-images.githubusercontent.com/602265/32317198-4b9bf300-bfb3-11e7-896c-5c58d2cdab4d.jpg)

May I ask which version of OpenCOR you are using (probably your version + master changes?) and on which version of macOS you are?

**Comment by dbrnz** [comment]
Master plus my changes under High Sierra. I've just done a clean build from master and the issue is still there.

Hmm, I've just noticed that `qmake --version` reports version 5.9.0 and yet I'm sure I upgraded to 5.9.2. Will try deleting the Qt installation and reinstalling.

**Comment by dbrnz** [comment]
My bad -- all is well with Qt 5.9.2.

**Comment by agarny** [comment]
Phew! I guess I am not surprised since Qt has been 'fixed' between Qt 5.9.1 and 5.9.2. Still, it goes to show that I should probably check for Qt 5.9.2 (and no other version, not even a later version; until the next LTS, at least) is being used to build OpenCOR (see commit a2e638fa24902f9b7f5878ab819c0fa36ac8f713).
