### ISSUE TITLE
CellML API: OpenCOR crashes if a metada id contains `:`

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1487]
Loading this CellML model will cause OpenCOR to crash (reproducibly) on at least windows and mac: https://models.physiomeproject.org/workspace/4e3/rawfile/05b3384ebffa15c5270486a6b9249a3360e34ebf/Kapela_VSM.cellml

(This model was translated into CellML from an SemSim OWL model which in turn had come from a JSim model description. I've fixed, as far as I can tell, the units issues but the MathML is poorly formed as it is based on the JSim math.)

While the model is obviously invalid, it would be best not to crash :) I'm assuming this is likely an uncaught exception from the CellML API?

**Comment by agarny** [comment]
I can indeed confirm that the model crashes OpenCOR (since OpenCOR 0.3 when we introduced the opening of remote files). I am going to have a look at it, but from past experiences I would indeed also assume that the issue has something to do with units in the CellML API. Argh! :(

**Comment by agarny** [comment]
FWIW, the problem seems to be directly/indirectly related to a call to `RDFAPIRepresentation::source()`... Time to debug the CellML API...

**Comment by agarny** [comment]
To remove the RDF code from https://models.physiomeproject.org/workspace/4e3/rawfile/05b3384ebffa15c5270486a6b9249a3360e34ebf/Kapela_VSM.cellml solves the problem, i.e. the model doesn't crash OpenCOR anymore (the model itself does have issues though).

**Comment by agarny** [comment]
Ok, found the culprit. In the RDF code, there are things like:

```
<rdf:Description rdf:about="#h_IP3:time">
  <dcterms:description>Rate of change of IP3 receptor activation gate open probability</dcterms:description>
</rdf:Description>
```

Now, the problem is that `rdf:about` is equal to `#h_IP3:time`, i.e. it contains `:`. Sure enough, if I remove that RDF element and all the others that have an `rd:about` value that contains `:`, then OpenCOR can open the file just 'fine'.

Looking at the CellML API code, I had to modify it a tiny bit to get things to work (see [here](https://github.com/cellmlapi/cellml-api/commit/d7baf9038e42859fa96117db6c9644f9f09ecf8b)).
