### ISSUE TITLE
Installation license view shows "English(France)" as the language selection

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1514]
Just installed the 2017-12-23 snapshot and when the installer gets to the license display the (only) language comes up "English (France)" - not sure if this has always been the case, but just noticed it and thought maybe it should be something more like "English (UK)" or "English (NZ)"  :-)

**Comment by agarny** [comment]
Hmm, indeed, it changed from `English (United Kingdom)` to `English (France)` (!!) between the `2017-09-25` and `2017-10-05` snapshots. I have no idea why and how that happened, but I will have a quick look.

**Comment by agarny** [comment]
Here are the [differences](https://github.com/opencor/opencor/compare/931292af5c74f975f03002a4215e98dcdd9fc887...8333d06d7565ccfe1e90aeb480f983646efe437c) between the `2017-09-25` and `2017-10-05` snapshots, and I can't see anything that could be responsible for that change...

**Comment by agarny** [comment]
Ok, it's because I had somehow changed my Regional settings. I have just reset them:

![screen shot 2018-01-09 at 09 35 07](https://user-images.githubusercontent.com/602265/34711639-66ba346a-f520-11e7-81c6-d65e3f90fa77.png)

 and now we are back to `English (United Kingdom)`:

![screen shot 2018-01-09 at 09 36 22](https://user-images.githubusercontent.com/602265/34711694-9bd0518e-f520-11e7-9505-bea718c439b0.png)

So, closing this issue. (Thanks for spotting it!)
