### ISSUE TITLE
Error messages in OpenCOR are not descriptive enough

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1565]
It is often more informative to export the cellML code to another user-defined format to view what the errors are, than see the message in OpenCOR. 

For example, in clancy_rudy_2001.cellml on PMR, commenting out line 130 for dVdt generates an error in the simulation tab:
" the model is unsuitably constrained (i.e. some variables could not be found and/or some equations could not be used)."

However, performing File Export (to MATLAB) generates more informative messages. Specifically line 26 says 
"Undefined: dVdt in component membrane in model  file:///C:" ... etc

Adding this feature to OpenCOR without having to export to another format would be helpful! 

[clancy_rudy_2001 - Exported.txt](https://github.com/opencor/opencor/files/1817748/clancy_rudy_2001.-.Exported.txt)

**Comment by agarny** [comment]
I fully sympathise. However, I am going to close this issue as won't do since we are waiting for [`libCellML`](https://github.com/cellml/libcellml) to become available to properly tackle the issue of CellML-related messages. In the meantime, you might want to use [COR](http://opencor.ws/cor/index.html), which provides much better and more accurate messages (caveats: it only works on Windows and only supports CellML 1.0).
