### ISSUE TITLE
PMR support: cannot synchronise more than one file at a time

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1571]
@s-fong reported this issue:
- Start OpenCOR and connect to your `PMR Workspaces`;
- Create a new workspace in the Staging instance of PMR;
- Make a local copy of the workspace you have just created;
- Add one file to the local copy of your workspace; and
- Synchronise your workspace with PMR.

At this stage, if you view your workspace in PMR, you will see that it indeed contains one file.

Now:
- Add two files to the local copy of your workspace; and
- Synchronise your workspace with PMR.

Here, you would expect things to work as above, it does not. OpenCOR may either:
- have its busy widget running indefinitely, forcing you to kill OpenCOR; or
- get an error message that reads `request failed with status code 502`.

From there, if you go to the command line and do `git status`, you will get something like:

```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

If you then do `git push` as suggested, then everything is fine:

```
$ git push
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 486 bytes | 486.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0)
To https://staging.physiomeproject.org/workspace/28b
   c46ba62..a53f77c  master -> master
```

Looking at the OpenCOR code, the problem occurs [here](https://github.com/opencor/opencor/blob/2da70a50a9549dba9b9c577fb6f1d0f265c7d274/src/plugins/support/PMRSupport/src/pmrworkspace.cpp#L1331) when calling `git_remote_push()`. When adding one file, that call goes through fine, but when adding two files or more, that call hangs up or return the 502 error...!? @dbrnz, any idea what might be going wrong here?...

**Comment by agarny** [comment]
This is crazy, I have just done the following:
- Create a new workspace;
- Add several files/folders to it; and
- Synchronise things.

And, it all went through as confirmed by checking the workspace on PMR...!? @s-fong tried to do the same on her computer (Windows), but she got that 502 error once again...

**Comment by agarny** [comment]
@metatoaster, would you have any insight into what is happening here?...

**Comment by metatoaster** [comment]
The last time I had to [debug and fix](https://github.com/dulwich/dulwich/pull/262) interoperability issues between git implementation literally required a dump of the entire TCP session (which can be generated by tcpdump), so unless I have one of those dumps of the failures, I can't easily begin to see where went wrong.  Unfortunately, I am not in the position in being able to easily generate one of those dumps now, but I might be available in about three weeks.

That said, I can see that there are no HTTP 502 status codes for libgit2 being logged and reported by Apache over the last 48 hours, so I am not even sure where or how libgit2 got that as a status code.

**Comment by agarny** [comment]
Yes, not quite sure either. All I know is that I have never had that issue on macOS (just that the call to `git_remote_push()` may hang up). FWIW, @s-fong, who has had that issue, is running OpenCOR on Windows.

**Comment by dbrnz** [comment]
Under Windows 10 I've just tried s-fong's steps above and everything worked as expected. This is with a freshly built OpenCOR using the latest `master` branch.

**Comment by dbrnz** [comment]
@metatoaster, HTTP 502 is `Bad Gateway` (The server was acting as a gateway or proxy and received an invalid response from the upstream server.) Could something within @s-fong's Windows' configuration be responsible??

**Comment by metatoaster** [comment]
@dbrnz Yes I am well aware of what that response code is; what I was saying is that I was unable to find the relevant log entries related to that specific error code in the logs on the relevant server itself, otherwise I could potentially locate some kind of error on the server.  The lack of relevant log entries means this isn't going to be an easy error to hunt down.

**Comment by metatoaster** [comment]
@agarny I can potentially capture the specific error for @s-fong when I return to Auckland using my local development machine, as only then I can more easily set up the required things to generate the TCP traces, if this issue is caused by some kind of network related shenanigans.

**Comment by agarny** [comment]
@metatoaster, FWIW, @dbrnz has installed a piece of software on @s-fong to get her TCP traces. More on Dave's analysis soon, I guess.

Otherwise, I have just tried to create a new workspace, add 3 files to it, and synchronise things using OpenCOR on Windows 10 (virtual machine in VirtualBox) and everything works fine. I have then tried the same using OpenCOR on Ubuntu 16.04 LTS (VirtualBox machine too), but it failed:

![screen shot 2018-03-20 at 10 42 47 am](https://user-images.githubusercontent.com/602265/37624322-9e9b94ee-2c2c-11e8-8470-879ecc9908b2.png)

It looks like it might be a different issue though.

**Comment by agarny** [comment]
Ok, @dbrnz got the trace, but it contains a lot of encrypted information, so he suggested that @s-fong tries a special version of OpenCOR where HTTPS is replaced with HTTP for the different instances of PMR. @s-fong has just tried that special version of OpenCOR and... everything works fine. So, no more 502 error. In conclusion, it seems like with synchronisation with PMR fails when using HTTPS, but works using HTTP. Any suggestions as why that might the case @metatoaster?

**Comment by dbrnz** [comment]
The security layer used by `libgit2` depends on the platform:

* macOS 10.8 or newer: Apple's Security framework.
* Linux and older versions of macOS: OpenSSL.
* MS Windows: Windows' HTTP layers unless disabled when configuring libgit2, in which case OpenSSL is used.

For Windows should we use OpenSSL instead of Microsoft's code??

**Comment by agarny** [comment]
As discussed with @dbrnz, we are going to get `libgit2` to use OpenSSL on all three platforms, so as to be consistent and potentially avoiding platform-specific issues in the future.

**Comment by agarny** [comment]
So, @dbrnz has now updated our `libgit2` binaries to depend on our copy of `OpenSSL`. From there, I have generated a new version of OpenCOR for @s-fong to try. To synchronise with PMR doesn't generate the 502 error code anymore, but... it doesn't push things to PMR either (and no error code from `libgit2`). She has to go to a Git prompt and do `git push` to get things on PMR...!? @dbrnz, @metatoaster anymore suggestions?

**Comment by agarny** [comment]
Good news is that, on Ubuntu, I am not getting the TLS-related error anymore. IOW, I can now create a workspace, and then add several files to it at once.

**Comment by agarny** [comment]
... and just to confirm: it seems to be working fine on macOS too.

**Comment by dbrnz** [comment]
@agarny, @s-fong, what scheme is failing when trying PMR synchronisation under Windows?? `https`? `http`? Both schemes??

**Comment by agarny** [comment]
@dbrnz: I gave @s-fong an `https` version. Will check `http` tomorrow.

**Comment by dbrnz** [comment]
The staging instance of PMR (https://staging.physiomeproject.org/) has been reporting HTTP error 503 when accessed by a web-browser for at least the last 12 hours -- @metatoaster are you doing work on it??

**Comment by agarny** [comment]
Ok, some progress, I suppose (on @s-fong's Windows machine):
 - With `https`: synchronisation fails at the push stage. We must `git push` to see the changes on PMR.
 - With `http`: synchronisation goes through fine and the changes are visible on PMR. Note: due to current problems with the `staging` instance, @s-fong did the test using the `models` instance of PMR.

**Comment by agarny** [comment]
Breaking news: @s-fong just tried the `https` again, but this time on `models` instance (for the reasons mentioned above) and... it's all working fine! So, could it be that the `staging` instance is not configured in the same way as the `models` instance?

**Comment by dbrnz** [comment]
Hmm, the `models` web-server is configured to redirect `http` requests to `https`  (point a web-browser at http://models.physiomeproject.org/welcome and you always will get back `https`.) IOW there should be no difference between using `http` and `https` for the `models` instance.

**Comment by agarny** [comment]
Hmm, indeed... puzzled and puzzling...

**Comment by metatoaster** [comment]
Staging instance was down again for the last twelve hours. I am almost done the redeployment script and in fact I have an image generated, just running more tests on it before I push it to AWS and replace this dying staging instance.  Please try the staging instance again, I gave it a kick again.

**Comment by dbrnz** [comment]
Staging works for me using `https` under Windows. Awaiting @s-fong's testing with interest...

**Comment by agarny** [comment]
I am lost. @s-fong just tried again with `https` and the `staging` instance and she got a `502` error and doing `git status`, she gets:

```
$ git status
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
 
nothing to commit, working tree clean
```

**Comment by dbrnz** [comment]
What does `git remote -v` show??

**Comment by s-fong** [comment]
Here goes:

```
$ git remote -v
origin  https://staging.physiomeproject.org/workspace/313 (fetch)
origin  https://staging.physiomeproject.org/workspace/313 (push)
```

**Comment by metatoaster** [comment]
More details here about that specific error: https://stackoverflow.com/questions/21609781/why-call-git-branch-unset-upstream-to-fixup

Alternatively, if you have reused that local git checkout please try again with a fresh one.

**Comment by dbrnz** [comment]
Further to @metatoaster's comment, the `upstream is gone` message can be misleading (e.g. see this [Stackoverflow discussion](https://stackoverflow.com/questions/24870145/upstream-gone-message-on-switching-back-to-an-empty-master-branch/33660419)) and may indicate that the master branch on the remote repository is empty. This could be due to the synchronisation failure from OpenCOR.

So far as the 502 error goes, I'll need to build a special version of OpenCOR that saves the SSL secret key in a file so that Wireshark can decrypt traffic.

**Comment by agarny** [comment]
FWIW, I have just tried the "new" `https` version of OpenCOR with the `staging` instance on Windows (VirtualBox machine), and it's all working fine for me. So, it looks like it's only on @s-fong's computer that things are going awry.

**Comment by dbrnz** [comment]
OK, I'm wondering about the exact versions of Windows on the different systems. Does each have the same level of MS updates?? I'm running Windows 10 Pro, version 1703, OS Build 15063.674.

**Comment by agarny** [comment]
Personally, I am running Windows 10 Pro, version `1709`, OS Build `16299.309` while @s-fong is running Windows 10 Pro, version `1709`, OS Build `16299.248`.

**Comment by dbrnz** [comment]
@s-fong are you still getting the 502 failure using `https`? I now have a `git2.dll` to install into your OpenCOR that logs the SSL keys -- this means we can now decrypt a Wireshark capture file to (hopefully) see what's going on.

**Comment by s-fong** [comment]
@dbrnz yes, 502 error using https. 
I am at a DTP today, but should be around at lunch or after 4pm today for installing the dll file.

**Comment by dbrnz** [comment]
@s-fong I'll install things after 4pm today.

**Comment by dbrnz** [comment]
The HTTP conversation with Apache is:
```
Content-Length: 217
Expires: Tue, 01 Jan 1980 00:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, max-age=0, must-revalidate
X-Frame-Options: SAMEORIGIN
Content-Type: application/x-git-receive-pack-advertisement

001f# service=git-receive-pack
00000073be498a7951f44fcd7f3204b027b474a2a4871f6c HEAD. report-status delete-refs quiet ofs-delta side-band-64k no-done
003fbe498a7951f44fcd7f3204b027b474a2a4871f6c refs/heads/master
0000POST /workspace/506/git-receive-pack HTTP/1.1
User-Agent: git/2.0 (libgit2 0.26.3)
Host: models.physiomeproject.org
Accept: application/x-git-receive-pack-result
Content-Type: application/x-git-receive-pack-request
Transfer-Encoding: chunked
Authorization: Basic c2Zvbmc6YTgzNmRjMjYwNWIzNzZmMGE5ZTcxZWY1NGM2NGUwNmZlNzM3YzhlMA==
  .
  . Approx 4.6MB of data
  .
HTTP/1.1 502 Bad Gateway
Date: Thu, 22 Mar 2018 03:15:02 GMT
Server: Apache/2.4.10 (Debian)
Content-Length: 325
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Bad Gateway</title>
</head><body>
<h1>Bad Gateway</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at models.physiomeproject.org Port 443</address>
</body></html>
```

Googling "The proxy server received an invalid response from an upstream server" suggests that the proxy frontend (i.e. Apache) has timed out waiting for a response from PMR's backend. Because the files being pushed are several megabytes in size this seems likely. Indeed, everything works fine when @s-fong pushes much smaller files.

@metatoaster, are you able to increase the proxy timeout values? And do the backend logs show a dropped connection?

**Comment by metatoaster** [comment]
It's actually have to do specifically with the `chunked` encoding.  This is [a known bug](http://aucklandphysiomerepository.readthedocs.io/en/latest/workingwithworkspaces.html#troubleshoot), and is complicated by the fact that Zope/Plone backend also doesn't support that HTTP encoding correctly (and bitbucket had a [similar issue](https://stackoverflow.com/questions/10790232/hanging-at-post-git-receive-pack-chunked)).  In the standard git client the command `git config http.postBuffer 524288000` may be executed, and similarly OpenCOR should not use the chunked encoding.

**Comment by agarny** [comment]
From your second link, some people are saying that `git config http.postBuffer 524288000` didn't work for them and that they had to use `git config http.postBuffer 5242` instead. So, which one can we "safely" use?...

**Comment by metatoaster** [comment]
That particular context is that particular server uses nginx as a front end and that was configured to reject large files, hence the small transfer size (using chunk encoding) is required for that case and is completely inapplicable for our use case and setup, as the current setup for PMR **does not** support chunk encoding.

**Comment by agarny** [comment]
Ok, thanks, got you. Will therefore try `git config http.postBuffer 524288000` on @s-fong's computer and see how it goes. Then, we will have to see whether the same can be done by OpenCOR through `libgit2` (which should be the case, I reckon).

**Comment by dbrnz** [comment]
Changing `http.postBuffer` is not going to do anything -- see https://github.com/libgit2/libgit2/issues/3981#issuecomment-257518324:
> libgit2 does not have a POST buffer, we do require the remote end to accept chunked encoding when we send the packfile.

In other words, PMR does not support `libgit2` clients that use `http` transport schemes (this includes `https`) as it may fail when pushing large files. @metatoaster, does PMR accept `ssh` or `git+ssh` clients?? And could PMR return much more friendly error messages when its limitations are breached??


Having said this, what we have been seeing here is Apache's proxy front-end timing out when using `https` but all working fine when using `http`. I don't know how Apache is configured on PMR, but this suggests to me that `mod_proxy` (or similar) is handling the SSL layer and that if @metatoaster were to increase the timeout values on the `ProxyPass` directive we would pass this particular hurdle.

In general it may be useful for OpenCOR's user documentation to note PMR's [caveat on having large binary files in a workspace](http://aucklandphysiomerepository.readthedocs.io/en/latest/workingwithworkspaces.html#other-hints-and-tips) and make users aware that although OpenCOR provides a user-friendly interface to PMR workspaces this is only intended for the storage of models, simulations and related data/metadata, not large MS Word files and other documents... @s-fong is one user who thinks a PMR workspaces is cloud storage with versioning, which it isn't! :) :)

**Comment by s-fong** [comment]
$ git status
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   luo_rudy_model (modified content, untracked content)

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by metatoaster** [comment]
> does PMR accept ssh or git+ssh clients??

No, I had explored how this might be done and it turns out there will be a bit of work involved, as I also need to provide ssh key management for that backend and we (@nickerso and I) decided that we will defer that to when we make the decision to use gitlab for a more complete solution.

> And could PMR return much more friendly error messages when its limitations are breached??

Not really, not without a lot of work as these error messages are generated by either Apache and to a lesser extent Dulwich (through the git wire protocol).

> Having said this, what we have been seeing here is Apache's proxy front-end timing out when using https but all working fine when using http. I don't know how Apache is configured on PMR, but this suggests to me that mod_proxy (or similar) is handling the SSL layer and that if @metatoaster were to increase the timeout values on the ProxyPass directive we would pass this particular hurdle.

As I said before, it's the inability of Zope backend as it cannot handle chunked encoding, it is not a matter of timeouts being too low. Also, I haven't been able to get Apache to rewrite the chunked request into a single request. I can't figure out why Apache 2.4 doesn't seem to be able to "dechunk" requests via `SetEnv proxy-sendcl 1`.

**Comment by agarny** [comment]
Ok, it looks like we might have reached a dead end. So, as far as I can see it, we can either:
- Use `http` (rather than `https`) since it seems to be working with big files; or
- Keep using `https` and let OpenCOR users that they can't synchronise big files using OpenCOR.

I don't like the idea of telling people that they can't do this or that. So, I would favour option 1, but is that really what we want to do?... @metatoaster @dbrnz @nickerso

**Comment by metatoaster** [comment]
No, I will be turning off HTTP support as it is insecure, and that the rest of the world is basically also turning that off. Also, I hate to repeat myself, but it has to do with **chunked** encoding not being supported by the Zope backend, and if chunked encoding was used with *or* without https the same error will manifest.

**Comment by dbrnz** [comment]
> if chunked encoding was used with or without https the same error will manifest.

@metatoaster, my point is that we are not seeing a manifestation of the error you are refer to, since  in this particular example `http` works and the Apache proxy is only timing out when handling `https`.

Although Zope doesn't support chunked encoding, meaning that both `http` and `https` will fail with sufficiently large transfers (and some other error message??), given that `mod_proxy` allows timeout values to be specified, why not simply increase the timeout??? Yes, we will still get failures but there should be fewer of them, especially if users take note of warnings about using PMR to store large files.

**Comment by metatoaster** [comment]
Can you please verify that the same chunked encoding worked over `http`, please provide HTTP headers.

As for not increasing the timeout, it's because as I said, Zope does not support chunked encoding.  Servers that do not support the chunked encoding sees the request terminated with the first chunk, and it goes off and does processing and either errors out or provide a response when Apache does not expect it, thus Apache never gets a response anyway so any increase in timeout values (the default is 60 seconds which is _plenty_ long).

**Comment by agarny** [comment]
Fair enough about `http` support being turned off at some point.

Anyway, I thought that `http` was working with big files, but I clearly got confused (then again, we have tried so many different things these past few days!) since I have just tried to synchronise a big file using OpenCOR (on my macOS machine) and I got that famous `502` error (so, the same as with `https`, as already observed), and it's the same from the command line (as expected).

So, the bottom line really seems to be that we should update the documentation to let people know that they can't use PMR with big files. What is the size limit though?

**Comment by metatoaster** [comment]
Whatever libgit2 sets as a threshold for breaking the push body into multiple chunks, it may be about 1MB in size, as I can't find a clear documentation on this.

Also, it's not just large files, this issue can also manifest with enough commits that push the pack size over the limit that libgit2 [decides to break it into multiple chunks](https://github.com/libgit2/libgit2/blob/408b16c1b06526f509fdb8997818d648d4d1ea1e/src/transports/http.c#L210); perhaps this can be changed for the version OpenCOR uses to ensure that chunked encoding is not used.

Or I could find a proper reverse proxy that actually works. Apache 2.4 clearly doesn't work.

As an aside, some years ago I spent a long time trying to debug and fix this, but the issue lies in the very ancient Medusa HTTP server and how Zope dispatches requests based upon it, and that is some gnarly Python code so I never got around to try to fix it.  While chunked encoding is supported it is only for sending data (and to trigger that feature requires certain gymnastics), not for receiving (which is this case), as that server makes the assumption that any HTTP request is received as one body (thus any further chunks are dropped and ignored).

**Comment by agarny** [comment]
Good point, @metatoaster, about trying to change the version of `libgit2` used by OpenCOR. I am going to give it a try.

**Comment by nickerso** [comment]
Just to jump into this discussion.... We need to be careful not to invest too much effort in addressing this edge case as we will be overhauling the PMR Git infrastructure in the next few months - likely to be using GitLab - which will hopefully remove the need for these special snowflakes. I suggest the easiest option going forward is to try and catch cases like this that fail and present appropriate error messages to the user to help them realise what is wrong. I think we don't want to be putting too much new smarts into the OpenCOR use of Git until we move to the new infrastructure and have a stable platform going forward.

**Comment by agarny** [comment]
I spent a few minutes to try to alter `libgit2`, but to no avail. I am still getting an error at some point or another when trying to synchronise a big file to PMR. (@dbrnz: I didn't find another version of `libgit2`, I just meant tweaking the code to bypass the use of chunks.)

Anyway, I agree @nickerso, not worth spending more time on this. I am therefore going to see what can be done on the OpenCOR front to provide the user with a suitable error message.

**Comment by agarny** [comment]
Actually, I am not going to bother with a suitable error message. We are already getting a 502 error from Git, so will stick to this. So closing.
