### ISSUE TITLE
Some seemingly random crashes may occur (especially on Windows)

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1574]
Editing a .cellml file on snapshot OpenCOR-2018-03-17-Windows 
The corresponding .sedml file is open in another tab which is dependent on the .cellml file.
When saving the .cellml file with Ctrl-S, OpenCOR crashed!

**Comment by s-fong** [comment]
Addendum: closed the .sedml file and continued editing .cellml
Saved .cellml and tried reopening the sedml file in a new tab, when crash happened!
![20-mar](https://user-images.githubusercontent.com/37389207/37631684-c7a0d9c6-2c4f-11e8-97fa-ee3053b3b1ee.PNG)

**Comment by agarny** [comment]
Ok, the "good" news is that I am able to reproduce the problem on Windows, Linux and macOS:
1. Opened OpenCOR's test noble_1962_local.sedml file;
2. Asked for the corresponding CellML file;
3. Edited the CellML file;
4. Saved the CellML;
5. Answered yes to reloading the SED-ML file;
6. Go back to step 3.

Eventually, OpenCOR will crash at step 4. From the crash report (on macOS), this has to do with the data store, which I didn't expect at all since I thought it might have something to do with the `Simulation Experiment` view being updated (while hidden). (Good thing that it's not working on macOS and that we get a crash report on that platform since everything seems to be working fine in debug mode...!?)

[OpenCOR-macOS-dump.txt](https://github.com/opencor/opencor/files/1828706/OpenCOR-macOS-dump.txt)

**Comment by s-fong** [comment]
Tried opening another file in simulation view and OpenCOR consistently crashes (window not responding). This happened 4 consecutive times from latest snapshot, even after closing all existing tabs.

Code available at 
https://github.com/uomsystemsbiology/bond_graph_cardiac_AP/tree/master/CellML
where crash happens for any of these 3 files.

**Comment by agarny** [comment]
Ok, you will have to show me that tomorrow. I have just tried with one of the files on Windows and macOS, and OpenCOR doesn't crash, but it is completely unresponsive. I wonder whether they are not too big for the CellML API? @nickerso, didn't you or one of your students have a similar problem at some point?...

**Comment by nickerso** [comment]
I can confirm that I get the same behaviour (OpenCOR becomes unresponsive when switching to simulation view with those models). We did have a similar problem with models generated with huge piecewise's in them (representing data), but seem to recall that being more an issue with the text view in OpenCOR rather than the switching to the simulation view (but could also be related to memory in the CellML API).

**Comment by agarny** [comment]
The crash report I got on macOS gave me the impression that it might have been a memory issue. Will have a proper look tomorrow.

**Comment by agarny** [comment]
FWIW, I have just tried one of the models in `COR` and... after replacing:

```
var t: second {init: 0};
```

with:

```
var t: second;
```

I can now go into simulation mode (note: I am not able to run the model, but that's another issue):

![image2](https://user-images.githubusercontent.com/602265/37697208-62a291f8-2d40-11e8-9eed-a1b2a1aff49f.png)

So, for me, it looks very much like a memory-related CellML API issue.

**Comment by agarny** [comment]
FWIW, a few improvements have been made, which hopefully will improve the overall stability of OpenCOR.

**Comment by agarny** [comment]
A few steps that will result in a crash:
1. Start OpenCOR;
2. Open OpenCOR's `noble_1962_local.sedml` file;
3. Run the corresponding simulation;
4. Switch to the `Raw SED-ML` view;
5. Edit the SED-ML file and save it;
6. May want to switch back to the `Simulation Experiment` view and check that things are fin; and
7. Go back to step 4.

At some point, step 5 should result in a crash in `SimulationExperimentViewSimulationWidget::data()`, i.e. OpenCOR tries to access some simulation results, which don't seem to exist. So, something to investigate!
