### ISSUE TITLE
Simulation Experiment view: keep track of unselected graphs in a SED-ML file / COMBINE archive

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1631]
When a graph panel has more than one plot but some are unticked, they disappear when OpenCOR is closed and opened again. It would be great if all plots are saved in the sedml file - ticked or not - and upon reponening OpenCOR, carry over the ticked status from the previous session.

**Comment by agarny** [comment]
My initial thought was to have an annotation to specify whether a graph should be ticked or not (i.e. shown or not). However, this wouldn't necessarily work for another SED-ML capable tool. Indeed, such a tool wouldn't necessarily understand the annotation and would therefore, and by default, consider it as being "ticked", and would therefore display it, which is not what we want here. So, instead, we could, for a given curve, still generate the same SED-ML code, except that that code would be within an annotation for a list of "unticked" curves.

**Comment by agarny** [comment]
> My initial thought was to have an annotation to specify whether a graph should be ticked or not (i.e. shown or not). However, this wouldn't necessarily work for another SED-ML capable tool. Indeed, such a tool wouldn't necessarily understand the annotation and would therefore, and by default, consider it as being "ticked", and would therefore display it, which is not what we want here. So, instead, we could, for a given curve, still generate the same SED-ML code, except that that code would be within an annotation for a list of "unticked" curves.

The same should be done for a graph panel. Indeed, we may have a graph panel with no graphs (or non-ticked graphs), in which case we might still want to export them, but through an annotation element.

**Comment by agarny** [comment]
Ok, in the end, to have a graph panel / graph in an annotation is proving to be a lot of work. Indeed, say that you have three graph panels and that the second one doesn't have any graphs, then that the second graph panel would need to be within an annotation. So far so good. However, XML elements can be serialised in any order, which means that we might want to have a `position` attribute or something to keep track of the position of a graph panel. To serialise a graph panel that way is relatively easy (see commits e98ff8b and 933e210), but read them back is quite a bit more tedious since some graph panels would have to be retrieved the normal way and others from annotations. Then, there is the case of graphs themselves. So, in the end, we are simply going to have a simple annotation to determine whether a graph is selected or not. This means that, as for CellML files, it will be up to the end-user to clean up their SED-ML file before publishing it.

**Comment by agarny** [comment]
Oops, although we do now track the selected state of a graph, when reopening a CellML file / COMBINE archive and running it, OpenCOR plots everything, including unselected graphs...! So, reopening...
