### ISSUE TITLE
Simulation Experiment view: doubling of y axis on a graph when simulation has run

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1683]
[L_Ca_channel.zip](https://github.com/opencor/opencor/files/2078983/L_Ca_channel.zip)

**Comment by agarny** [comment]
I can indeed confirm the issue on Windows and Linux (not on macOS though):

![windows](https://user-images.githubusercontent.com/602265/41079275-49029758-6a75-11e8-91d2-493ecd038616.png)

![linux](https://user-images.githubusercontent.com/602265/41079281-4e588bf4-6a75-11e8-928e-1211f00caba1.png)

**Comment by agarny** [comment]
FWIW, the issue at hand occurred because of something we did to fix another issue. However, and ideally, that other fix shouldn't have been necessary in the first place. So, we removed it (see commit 
6d55e13) and, thus, fixed the issue at hand, which means that we now need to fix that other issue (see issue #1696).
