### ISSUE TITLE
CellML-based views: can't show a CellML file that cannot be fully instantiated

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1725]
In a .cellml file, when switching between text editor/simulation view, weird behavior happens when there is an error within the text view. Text from Cellml Text view disappears, when going from Editing to Simulation View! Text is still present in raw cellml view. Then going from Editing back to Simulation View, I get a blank scsreen which reads "The Simulation Experiment view does not support this type of file..."
I have to close and reopen the tab for that file to see text again.

The error for the file main_BG_7.cellml (that made text disappear) read:
“Error: the imports could not be fully instantiated (C:/Users/sfon036/Google Drive/2018_work/BOND_GRAPHS/clancy_models/CR_BG_components/main_BG_7.cellml imports ca_dynamics_JRW_2/ca_subsystem.cellml, which contents could not be retrieved).”
[OpenCOR 27_06_2018snapshot_error.zip](https://github.com/opencor/opencor/files/2164382/OpenCOR.27_06_2018snapshot_error.zip)

**Comment by agarny** [comment]
Thanks @s-fong and sorry for that problem. The video is very useful, although it would have been nice to have some sample files to reproduce the issue. Still, I was able to reproduce it. So, mainly for my own record:
- (Temporarily) rename OpenCOR's `cellml_1_1/components/units.xml` file to `cellml_1_1/components/xunits.xml`; and
- Open the `cellml_1_1/experiments/periodic-stimulus.xml` file in OpenCOR.

At this stage, we will see something like using the `CellML Text` view:

![screen shot 2018-07-05 at 11 04 58 am](https://user-images.githubusercontent.com/602265/42313556-5655e0e8-8043-11e8-96f4-b24d7c854782.png)

Then, because we `broke` an import, to switch to the `Simulation Experiment` view will result in an error message:

![screen shot 2018-07-05 at 11 05 02 am](https://user-images.githubusercontent.com/602265/42313558-58b979d0-8043-11e8-9d91-17c50fb7e808.png)

Then, trying to switch back to the `CellML Text` view, we can indeed see that the view says that it doesn't support this type of file:

![screen shot 2018-07-05 at 11 05 05 am](https://user-images.githubusercontent.com/602265/42313572-5e37897e-8043-11e8-95c0-f9af52caa8df.png)

while the `Raw CellML` view still works as expected:

![screen shot 2018-07-05 at 11 05 07 am](https://user-images.githubusercontent.com/602265/42313576-61579a5e-8043-11e8-99da-14105205eee4.png)

**Comment by agarny** [comment]
FWIW, I get the feeling that it might be related to the side work that I have done in preparation of CellML 2.0 (see issue #1703). Indeed, the way a CellML-based view now checks whether a file is a CellML file is slightly different, which would explain the observed behaviour.

**Comment by agarny** [comment]
FWIW, yes, this is definitely that since the 2018-06-27 snapshot (used here) implements that side work for the `CellML Text` view, but not the `Raw CellML` view. Ok, should be "easy" to fix then.
