### ISSUE TITLE
Seg fault error

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1750]
I'm trying to build and run it on Ubuntu 18.04.
Compiling is successful but running gives me seg fault error.

**Comment by agarny** [comment]
Hmm, strange. I have just created a virtual machine with Ubuntu 18.04 LTS and the prerequisites for OpenCOR. From there, I was able to build OpenCOR just fine, as well as (kind of) run it:
 
![screen shot 2018-08-06 at 10 46 01 am](https://user-images.githubusercontent.com/602265/43706545-f2da2ab0-9965-11e8-8279-90d74c33624c.png)

We can see that there is an issue with OpenSSL. From [here](https://stackoverflow.com/questions/43546301/error-creating-ssl-context#), it looks like it is because Ubuntu 18.04 LTS uses a more recent version of OpenSSL and, indeed, it uses version 1.1.0g while we use version 1.0.2o.

At some point (see issue #1088), we did try to move to the 1.1.x branch of OpenSSL, but it was causing us problems with `libgit2` (ping @dbrnz). That was 2 years ago, so we should revisit this issue, if anything so that OpenCOR can work fine on Ubuntu 18.04 LTS (see issue #1751).

**Comment by agarny** [comment]
After moving to OpenSSL's 1.1.x branch and rebuilding OpenCOR from scratch, OpenCOR now works fine on Ubuntu 18.04 LTS:

![screen shot 2018-08-06 at 2 14 21 pm](https://user-images.githubusercontent.com/602265/43716107-289b8adc-9983-11e8-8159-a51403b194c2.png)

@ssafaei, could you please try to build OpenCOR from scratch? I.e.

```
$ cd [OpenCOR]
$ ./cleanall
$ ./make
$ ./run
```

**Comment by ssafaei** [comment]
Thanks Alan, it's working fine now :)

**Comment by agarny** [comment]
Ok, so I take it that your build environment got "dirty" at some point. Anyway, closing then.
