### ISSUE TITLE
FMI support

### ISSUE THREAD

**Issue by filip-jezek** [opencor/opencor#1841]
Functional mockup interface is a standard in model exchange and co-simulation. Given the possibility of export the cellml models, they could be used in other tools and combined with other models, implemented in different tools or even languages, such as matlab, modelica, python etc..

**Comment by agarny** [comment]
Thanks @filip-jezek for the suggestion. I must confess that I had never heard of FMI before. @nickerso, @dbrnz, @metatoaster (and anyone else?), have you ever heard of it?

**Comment by filip-jezek** [comment]
Hi, thanks for such quick answer! FMI is actually a big thing, just have a
look at all the modeling tools, that support it:
https://fmi-standard.org/tools/
Maybe not a standard in biomedical modeling yet, but definitely very handy.
Using fmi you can transport all cellml models to any other platform and
combine it with other models, post-process results etc. it does not allow
model authoring though, it is only a simulation tool. I am sure you have
your priorities set, but this would would open collaboration on so many
levels. Our group has recently developed a fmi driver to some proprietary
platform, so If you are interested, I think we can help you to orientate
yourself in what is FMI about and also help you with the implementation.

Best,
F/
ne 14. 10. 2018 v 16:19 odesílatel Alan Garny <notifications@github.com>
napsal:

**Comment by agarny** [comment]
We do indeed have our own priorities and I am afraid that FMI support is not currently one of them, not least since our community already has standards to exchange models (through [CellML](https://www.cellml.org/) indeed) and simulations (through [SED-ML](https://sed-ml.github.io/) using [COMBINE archives](http://co.mbine.org/documents/archive)).

Still, OpenCOR is a plugin-based environment, so I imagine that such support could be "easily" added to OpenCOR, and any help in that regards would be most welcome.

**Comment by agarny** [comment]
Closing this issue since we simply don't have the resources to work on this.
