### ISSUE TITLE
Linux: support Ubuntu 19.04 by shipping libtinfo.so.5

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#2075]
The binary version of OpenCOR is running fine on 19.04, but when it's compiled using 19.04 there is a missing shared library: libtinfo

**Comment by agarny** [comment]
I can indeed confirm the issue using Ubuntu 19.04. A quick investigation shows that:
- `libtinfo.so.5` is installed on "old" versions of Ubuntu while `libtinfo.so.6` is installed on Ubuntu 19.04.
- `libtinfo.so.5` is needed by Qt, not OpenCOR as such.

So, I am not sure there is much we can do about it when it comes to OpenCOR. The only thing I can suggest at this stage is to `sudo apt install libtinfo5`. I have just tried and it's all working fine.

I am leaving this open for now since I am not 100% with my current "fix".

**Comment by ssafaei** [comment]
Thanks Alan, worked for me too!

**Comment by agarny** [comment]
Ok, I have decided to ship `libtinfo.so.5` with OpenCOR, so that OpenCOR should work out-of-the-box on Ubuntu 19.04.
