### ISSUE TITLE
Simulation support: put all non-GUI initialisation code into support plugin

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2078]
Certain properties of a newly opened simulation are currently initialised by the experiment view's widgets, for instance a simulation's solver is set by `updateSolversProperties()` (of `SimulationExperimentViewSimulationWidget`). This means that unless relevant code is duplicated, a simulation opened outside of the GUI (e.g. by a Jupyter kernel) is not fully initialised.

All non-GUI initialisation code properly belongs to the Simulation Support plugin, which should be able to create a ready-to-run simulation from a loaded file.

**Comment by agarny** [comment]
Thanks @dbrnz.  Looking at the `SimulationExperimentViewSimulationWidget::updateSolversProperties()` method, I can see that it is often called as a result of interacting with the GUI.

It seems to me that what might be missing from the Simulation support plugin is what is actually in `SimulationExperimentViewSimulationWidget::initializeSimulation()`? Is that correct? If not, it would help if you could tell me what you think is missing, especially since you are making use of the Simulation support plugin from outside of OpenCOR's GUI.

**Comment by dbrnz** [comment]
My (incomplete) version of trying to initialise a simulation is in [simulationsupportpythonwrapper.cpp](https://github.com/dbrnz/opencor/blob/pythonplugin/src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp) from the `pythonplugin` branch.

**Comment by agarny** [comment]
I believe this has been (in part?) done?

**Comment by dbrnz** [comment]
This is complete, as otherwise we wouldn't be able to run headless simulations using Python.

**Comment by agarny** [comment]
Closing as per https://github.com/opencor/opencor/issues/2078#issuecomment-559435821.
