### ISSUE TITLE
Python: a clean build fails when building documentation

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2103]
See below -- restarting the build using `./make` succeeds.

I suspect this is due to changes in Python packaging between the `master` and `pythonplugin` branches. Possibly a missing dependency of the documentation build on `PythonPackages`??

```
[585/791] Performing configure step for 'userDocumentationBuild'
FAILED: ext/Stamp/userDocumentationBuild/userDocumentationBuild-configure 
cd /Users/dave/build/OpenCOR/build/ext/Build/userDocumentationBuild && /usr/local/Cellar/cmake/3.14.3/bin/cmake -DPYTHON_EXECUTABLE=/Users/dave/build/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python "-DSPHINX_EXECUTABLE=/usr/local/Cellar/cmake/3.14.3/bin/cmake;-E;env;PYTHONPATH=/Users/dave/build/OpenCOR/src/plugins/thirdParty/PythonPackages/ext/lib/python3.5/site-packages;/Users/dave/build/OpenCOR/src/plugins/thirdParty/PythonPackages/ext/bin/sphinx-build" -GNinja /Users/dave/build/OpenCOR/ext/doc/user && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E touch /Users/dave/build/OpenCOR/build/ext/Stamp/userDocumentationBuild/userDocumentationBuild-configure
CMake Error at /Users/dave/build/OpenCOR/build/ext/Build/userDocumentationBuild/theme/cmake/common.cmake:26 (message):
  Sphinx 1.4 or later is required...
Call Stack (most recent call first):
  CMakeLists.txt:26 (build_documentation)


-- Configuring incomplete, errors occurred!
See also "/Users/dave/build/OpenCOR/build/ext/Build/userDocumentationBuild/CMakeFiles/CMakeOutput.log".
[586/791] Performing configure step for 'developerDocumentationBuild'
FAILED: ext/Stamp/developerDocumentationBuild/developerDocumentationBuild-configure 
cd /Users/dave/build/OpenCOR/build/ext/Build/developerDocumentationBuild && /usr/local/Cellar/cmake/3.14.3/bin/cmake -DPYTHON_EXECUTABLE=/Users/dave/build/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python "-DSPHINX_EXECUTABLE=/usr/local/Cellar/cmake/3.14.3/bin/cmake;-E;env;PYTHONPATH=/Users/dave/build/OpenCOR/src/plugins/thirdParty/PythonPackages/ext/lib/python3.5/site-packages;/Users/dave/build/OpenCOR/src/plugins/thirdParty/PythonPackages/ext/bin/sphinx-build" -GNinja /Users/dave/build/OpenCOR/ext/doc/developer && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E touch /Users/dave/build/OpenCOR/build/ext/Stamp/developerDocumentationBuild/developerDocumentationBuild-configure
CMake Error at /Users/dave/build/OpenCOR/build/ext/Build/developerDocumentationBuild/theme/cmake/common.cmake:26 (message):
  Sphinx 1.4 or later is required...
Call Stack (most recent call first):
  CMakeLists.txt:26 (build_documentation)


-- Configuring incomplete, errors occurred!
```

**Comment by agarny** [comment]
Yes, restarting the build will work since everything will have been downloaded, etc.

All I know is that the documentation builds fine after a `cleanall`. I did some work on target dependencies recently because the documentation wouldn't always build fine after a `cleanall`. However, I had forgotten to update the Help window plugin, so that's what I did yesterday.

Bottom line:
 - The `Python` and `PythonPackages` plugins both add themselves as a dependency to `PROJECT_BUILD_TARGET` (see [here](https://github.com/opencor/opencor/blob/e1904fdd3de3a12027b77c6d6097791e87bfd9d7/src/plugins/thirdParty/Python/CMakeLists.txt#L542) and [here](https://github.com/opencor/opencor/blob/e1904fdd3de3a12027b77c6d6097791e87bfd9d7/src/plugins/thirdParty/PythonPackages/CMakeLists.txt#L156));
 - We check that the `PythonPlugin` and `PythonPackagesPlugin` targets exist before building a given documentation (see [here](https://github.com/opencor/opencor/blob/e1904fdd3de3a12027b77c6d6097791e87bfd9d7/cmake/common.cmake#L95));
 - Each documentation adds itself to the list of dependencies for `PROJECT_BUILD_TARGET` (see [here](https://github.com/opencor/opencor/blob/e1904fdd3de3a12027b77c6d6097791e87bfd9d7/cmake/common.cmake#L118)); and
 - The Help window plugin has a dependency on `PROJECT_BUILD_TARGET` (see [here](https://github.com/opencor/opencor/blob/e1904fdd3de3a12027b77c6d6097791e87bfd9d7/src/plugins/miscellaneous/HelpWindow/CMakeLists.txt#L7)).

Now, I am wondering whether the second step isn't what is causing you problems? I.e., the fact that we "only" check that the `PythonPlugin` and `PythonPackagesPlugin` targets exist rather than having a proper dependency on them?

Ok, I am going to improve this, which means that I will have to rethink the dependencies for the Help window plugin...

**Comment by agarny** [comment]
@dbrnz, could you please have a look at commit 05bb529 and see whether it fixes your problem?

**Comment by dbrnz** [comment]
All good with commit 05bb529, thanks @agarny.

**Comment by agarny** [comment]
Great, I am going to merge that in then. Cheers!
