### ISSUE TITLE
CellML support: improve the validation reporting of models with imports

### ISSUE THREAD

**Issue by Podde1** [opencor/opencor#2109]
I have been working with OpenCOR (version 0.6) for about 3-4 months now and it has been running errorfree until recently. 
While I was editing a rather big CellML file OpenCOR stopped responding when I switched from editing to the simulation view and I had to close the program. Every time I try to restart OpenCOR it is not responding. 
Prior to this, while I was working with the CellML file, when I saved changes OpenCOR would stop responding for about 2-5 seconds before saving the changes and responding again. I can not say if this happened every time I saved, but it occurred most of the times. 

After OpenCOR stopped responding completely, I tried in the following order. 
1) restart OpenCOR - OpenCOR did not respond and I closed the program
2) restart OpenCOR and wait for it to respond - I waited for about 20 min, it did not respond
3) restart the computer and start OpenCOR - OpenCOR did not respond 
4) uninstall OpenCOR and download it - OpenCOR is not responding 
5) Wait a day and try again - OpenCOR is not responding 

I have tried running OpenCOR on another Windows computer with the same files and it works there. The CellML file did most likely have an error present when I tried to enter the simulation view and OpenCORE stopped responding. I would have expected OpenCOR to show me an error message in the simulation view, but as I described above, instead OpenCOR stopped responding.

I am attaching the files that I worked with, in the status they were when the issue arose (the main  CellML file is where the issue occurred).
[ADAN-86-Heart-NVC.zip](https://github.com/opencor/opencor/files/3280812/ADAN-86-Heart-NVC.zip)

I have these versions 
OpenCOR 0.6
Windows 10 Home

**Comment by agarny** [comment]
Thanks a lot for the report and sorry that you are having troubles with OpenCOR 0.6.

I just tried your CellML and SED-ML files in OpenCOR 0.6 (and in our latest snapshot) on macOS 10.14 and I can indeed confirm the issue: OpenCOR hangs up. **So, I really wonder how come it is that your CellML and SED-ML files work fine with OpenCOR 0.6 on another Windows machine...?!**

Anyway, I am suspecting that it might have something to do with the CellML API (the API that we use to read/write CellML files), not least since you rely on imports. I am therefore going to look into it and see whether this is something that can be fixed or whether this is a case of your model being too "complex" for the CellML API.

In the meantime, and since everything seems to be working on a different Windows machine (!?), you might want to run the following command (from a DOS prompt): `OpenCOR -r`. This will reset all of OpenCOR, i.e. the next time you will be running OpenCOR, it will be as if you were to run it for the very first time. Give that a try and let me know how that goes.

**Comment by agarny** [comment]
Thanks again for the detailed report, that is very useful.

I can confirm that I was able to reproduce your problem on macOS with OpenCOR 0.6, as well as with the latest OpenCOR snapshot and my "personal" version of OpenCOR. **This makes wonder how come it works fine for you on a different Windows computer?!** A colleague of mine tried your model using the latest OpenCOR snapshot on his native Windows machine, and he had the problem you described.

Anyway, I have just a debug version of your model and I can see that the hanging is due to OpenCOR's attempt at generating compilable code for your model. To do this, we use the [CellML API](https://github.com/cellmlapi/cellml-api), which is not maintained anymore (it's due to be replaced by [libCellML](https://github.com/cellml/libcellml) at some point), and it looks like it just cannot generate compilable code for your model.

I have had a quick chat with @ssafaei and he reckons that it might be due to some erroneous mappings in your model. It's true that OpenCOR doesn't currently check for a model to be valid before trying to generate code for it. We do this because validation using the CellML API is costly (timewise) and, not only that, but there have been cases where the CellML API would be able to generate code for models that it considers to be invalid (!!). (Yes, that's one of the many reasons we are working on libCellML.)

Anyway, this means that you might to validate your model first before trying to simulate it. To that end, you will need to use the `Raw CellML` view since that's the only one (at this stage) that can do "proper" CellML validation. I have given it a try with your model and OpenCOR (through the CellML API) reported many issues, so that might explain why the CellML API is not able to generate code for your model. Still, it shouldn't hang like this (but there is nothing we can do about it since the CellML API is not being maintained anymore and it's due to be replaced by libCellML).

In summary:
 - You might want to run `OpenCOR -r` from the command (when in the OpenCOR directory) to reset your OpenCOR settings. This means that the next time you start OpenCOR, it will be as if you were running it for the very first time. From there, you should be able to open your model and validate using the `Raw CellML` view.
 - I am going to have a look at improving error reporting using the `Raw CellML` view. Indeed, the CellML API will report the same issue many times, if it is an issue that is present in a faulty imported CellML file (as is the case with your model). So, I need to ignore duplicated issues. Also, I might be able to provide better issue descriptions. Indeed, right now, this is the list of (non-duplicated) issues I am getting for your model, which as you can see is not very useful:

```
[Information] The issues reported below may be related to this CellML file and/or to one or several of its (in)directly imported CellML files.
[Error] [8:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Error] [17:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Error] [23:10] There is more than one variable in the same component called C_par.
[Error] [26:10] There is more than one variable in the same component called C_pvn.
[Error] [27:10] There is more than one variable in the same component called R_par.
[Error] [29:10] There is more than one variable in the same component called R_psh.
[Error] [30:10] There is more than one variable in the same component called R_pvn.
[Error] [31:10] There is more than one variable in the same component called I_par.
[Error] [33:10] There is more than one variable in the same component called I_psh.
[Error] [34:10] There is more than one variable in the same component called I_pvn.
[Error] [40:10] More than one connection to in interface of variable.
[Warning] [52:18] MathML equals element has inconsistent units between the sides.
[Warning] [72:18] MathML equals element has inconsistent units between the sides.
[Warning] [87:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [100:22] Expected all arguments to operator "plus" to have the same units.
[Warning] [104:18] MathML equals element has inconsistent units between the sides.
[Warning] [114:26] Units validation results may be incorrect because the exponent is not a constant.
[Warning] [115:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [128:26] Units validation results may be incorrect because the exponent is not a constant.
[Warning] [138:18] MathML equals element has inconsistent units between the sides.
[Warning] [143:22] Expected all arguments to operator "minus" to have the same units.
[Warning] [145:26] Expected all arguments to operator "plus" to have the same units.
[Warning] [154:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [183:22] Expected all arguments to operator "minus" to have the same units.
[Warning] [185:26] Expected all arguments to operator "plus" to have the same units.
[Warning] [190:18] MathML equals element has inconsistent units between the sides.
[Warning] [193:22] Expected all arguments to operator "plus" to have the same units.
[Warning] [223:22] Expected all arguments to operator "minus" to have the same units.
[Warning] [225:26] Expected all arguments to operator "plus" to have the same units.
[Warning] [270:18] MathML equals element has inconsistent units between the sides.
[Warning] [279:22] Expected all arguments to operator "minus" to have the same units.
[Error] [280:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [281:26] Expected all arguments to operator "minus" to have the same units.
[Warning] [308:34] Expected all arguments to operator "minus" to have the same units.
[Warning] [315:30] Expected all arguments to operator "gt" to have the same units.
[Warning] [320:22] Inconsistent units between pieces and otherwise of the piecewise equation.
[Warning] [344:18] MathML equals element has inconsistent units between the sides.
[Warning] [359:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [376:18] MathML equals element has inconsistent units between the sides.
[Warning] [387:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [410:18] MathML equals element has inconsistent units between the sides.
[Warning] [426:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [462:18] MathML equals element has inconsistent units between the sides.
[Warning] [465:22] Expected all arguments to operator "plus" to have the same units.
[Error] [552:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [617:18] MathML equals element has inconsistent units between the sides.
[Warning] [632:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [649:18] MathML equals element has inconsistent units between the sides.
[Warning] [660:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [683:18] MathML equals element has inconsistent units between the sides.
[Warning] [699:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [735:18] MathML equals element has inconsistent units between the sides.
[Warning] [738:22] Expected all arguments to operator "plus" to have the same units.
[Error] [869:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [935:18] MathML equals element has inconsistent units between the sides.
[Warning] [950:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [967:18] MathML equals element has inconsistent units between the sides.
[Warning] [978:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1001:18] MathML equals element has inconsistent units between the sides.
[Warning] [1017:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1053:18] MathML equals element has inconsistent units between the sides.
[Warning] [1056:22] Expected all arguments to operator "plus" to have the same units.
[Error] [1190:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [1259:18] MathML equals element has inconsistent units between the sides.
[Warning] [1274:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1300:18] MathML equals element has inconsistent units between the sides.
[Warning] [1311:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1334:18] MathML equals element has inconsistent units between the sides.
[Warning] [1350:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1395:18] MathML equals element has inconsistent units between the sides.
[Warning] [1398:22] Expected all arguments to operator "plus" to have the same units.
[Error] [1545:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [1612:18] MathML equals element has inconsistent units between the sides.
[Warning] [1627:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1653:18] MathML equals element has inconsistent units between the sides.
[Warning] [1664:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1687:18] MathML equals element has inconsistent units between the sides.
[Warning] [1703:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1739:18] MathML equals element has inconsistent units between the sides.
[Warning] [1742:22] Expected all arguments to operator "plus" to have the same units.
[Error] [1859:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [1924:18] MathML equals element has inconsistent units between the sides.
[Warning] [1939:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1956:18] MathML equals element has inconsistent units between the sides.
[Warning] [1967:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [1990:18] MathML equals element has inconsistent units between the sides.
[Warning] [2006:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2042:18] MathML equals element has inconsistent units between the sides.
[Warning] [2045:22] Expected all arguments to operator "plus" to have the same units.
[Error] [2141:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [2209:18] MathML equals element has inconsistent units between the sides.
[Warning] [2224:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2241:18] MathML equals element has inconsistent units between the sides.
[Warning] [2252:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2275:18] MathML equals element has inconsistent units between the sides.
[Warning] [2291:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2327:18] MathML equals element has inconsistent units between the sides.
[Warning] [2330:22] Expected all arguments to operator "plus" to have the same units.
[Error] [2478:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [2543:18] MathML equals element has inconsistent units between the sides.
[Warning] [2558:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2575:18] MathML equals element has inconsistent units between the sides.
[Warning] [2586:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2609:18] MathML equals element has inconsistent units between the sides.
[Warning] [2625:34] Expected all arguments to operator "plus" to have the same units.
[Warning] [2661:18] MathML equals element has inconsistent units between the sides.
[Warning] [2664:22] Expected all arguments to operator "plus" to have the same units.
[Error] [6385:10] Connection of components which are encapsulated in the hidden set of each other.
[Error] [6386:10] Mapping variable_2 which has private interface of none.
[Error] [6387:10] Mapping variable_2 which has private interface of none.
[Error] [6388:10] Mapping variable_2 which has private interface of none.
[Error] [6389:10] Mapping variable_2 which has private interface of none.
[Error] [6390:10] Mapping variable_2 which has private interface of none.
[Error] [6391:10] Mapping variable_2 which has private interface of none.
[Error] [6392:10] Mapping variable_2 which has private interface of none.
[Error] [6393:10] Mapping variable_2 which has private interface of none.
[Error] [6394:10] Mapping variable_2 which has private interface of none.
[Error] [6395:10] Mapping variable_2 which has private interface of none.
[Error] [6398:10] Connection of components which are encapsulated in the hidden set of each other.
[Error] [6399:10] Mapping variable_2 which has private interface of none.
[Error] [6400:10] Mapping variable_2 which has private interface of none.
[Error] [6401:10] Mapping variable_2 which has private interface of none.
[Error] [6402:10] Mapping variable_2 which has private interface of none.
[Error] [6403:10] Mapping variable_2 which has private interface of none.
[Error] [6404:10] Mapping variable_2 which has private interface of none.
[Error] [6405:10] Mapping variable_2 which has private interface of none.
[Error] [6406:10] Mapping variable_2 which has private interface of none.
[Error] [6407:10] Mapping variable_2 which has private interface of none.
[Error] [6408:10] Mapping variable_2 which has private interface of none.
[Error] [6409:10] Mapping variable_2 which has private interface of none.
[Error] [6410:10] Mapping variable_2 which has private interface of none.
[Error] [6411:10] Mapping variable_2 which has private interface of none.
[Error] [6412:10] Mapping variable_2 which has private interface of none.
[Error] [6413:10] Mapping variable_2 which has private interface of none.
[Error] [6414:10] Mapping variable_2 which has private interface of none.
[Error] [6415:10] Mapping variable_2 which has private interface of none.
[Error] [6416:10] Mapping variable_2 which has private interface of none.
[Error] [6417:10] Mapping variable_2 which has private interface of none.
[Error] [6418:10] Mapping variable_2 which has private interface of none.
[Error] [6419:10] Mapping variable_2 which has private interface of none.
[Error] [6420:10] Mapping variable_2 which has private interface of none.
[Error] [6421:10] Mapping variable_2 which has private interface of none.
[Error] [6422:10] Mapping variable_2 which has private interface of none.
[Error] [6425:10] Connection of components which are encapsulated in the hidden set of each other.
[Error] [6426:10] Mapping variable_2 which has private interface of none.
[Error] [6427:10] Mapping variable_2 which has private interface of none.
[Error] [6428:10] Mapping variable_2 which has private interface of none.
[Error] [6429:10] Mapping variable_2 which has private interface of none.
[Error] [6430:10] Mapping variable_2 which has private interface of none.
[Error] [6431:10] Mapping variable_2 which has private interface of none.
[Error] [6432:10] Mapping variable_2 which has private interface of none.
[Error] [6433:10] Mapping variable_2 which has private interface of none.
[Error] [6434:10] Mapping variable_2 which has private interface of none.
[Error] [6435:10] Mapping variable_2 which has private interface of none.
[Error] [6473:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Error] [6475:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Error] [6476:10] Variables with public or private interfaces of in cannot have initial value attributes.
[Warning] [6487:18] MathML equals element has inconsistent units between the sides.
[Error] [6662:10] Connection of two variables which have dimensionally inconsistent units.
[Error] [6694:10] The can only be a single connection element for each pair of components in the model.
[Error] [6694:10] There is more than one connection element for the same pair of components.
[Error] [6698:10] Connection of components which are encapsulated in the hidden set of each other.
[Error] [6699:10] Mapping variable_2 which has private interface of none.
[Error] [6702:10] Connection of components which are encapsulated in the hidden set of each other.
[Error] [6702:10] The can only be a single connection element for each pair of components in the model.
[Error] [6702:10] There is more than one connection element for the same pair of components.
[Error] [6703:10] Mapping variable_2 which has private interface of none.
```

**Comment by agarny** [comment]
@Podde1 and @ssafei: as you can see, I have made some improvements to OpenCOR. I am hoping to generate a new snapshot sometime within the next few days.

@Podde1: there is not much we can do about the freezing you get when trying to open your model using the `Simulation Experiment` view (the problem is related to the CellML API, which is a third-party library that I don't want to touch). However, I have improvement the reporting of validation issues in CellML files that have imports. This should therefore make it easier for you to identify and fix the various issues with your model. For this, just open your master CellML file using the `Raw CellML` view and validate it (by pressing `Ctrl`+`T`).

Hopefully, this should prove useful, but don't hesitate to get back to us (through GitHub) if you think things could be improved further.

**Comment by Podde1** [comment]
@agarny thanks for the fast response to this. To clarify what I meant with the file working on another window computer. So after my OpenCOR stop responding I sent over the files to another and tried them there. The files did not work there, the error was still present (I suspect that I had initial values for a private variable) but OpenCOR did not stop responding on that computer. I might have removed some changes I did prior to crashing the session on my computer, I can't recall exactly, unfortunately. 

Clearing the OpenCOR settings in the command prompt made it possible to run OpenCOR again.

**Comment by agarny** [comment]
> @agarny thanks for the fast response to this. To clarify what I meant with the file working on another window computer. So after my OpenCOR stop responding I sent over the files to another computer and tried them there. The files did not work there, the error was still present (I suspect that I had initial values for a private variable) but OpenCOR did not stop responding on that computer. I might have removed some changes I did prior to crashing the session on my computer, I can't recall exactly, unfortunately.

So, if it still didn't work on the other computer (as I would expect), what happened exactly when you are saying that it didn't stop responding? Did you get an error message?

> Clearing the OpenCOR settings in the command prompt made it possible to run OpenCOR again.

At least, that's a start! :)
