### ISSUE TITLE
Python support: add some Python-based tests

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2178]
A simple example of what a test might look like.

Specify a test as say `./python/test.py`:
```
# Import OpenCOR's Python module
import OpenCOR as oc

# Open a remote simulation (URL of a CellML or SEDML file)
s = oc.openRemoteSimulation('https://models.physiomeproject.org/workspace/25d/rawfile/f0e63e292ebb1d6798da08914b4217aec434af96/lorenz.sedml')

# Access the simulation's initial conditions
d = s.data()

# Changing simulation range
d.setStartingPoint(1)
d.setEndingPoint(2)
d.setPointInterval(0.01)

# Change constant parameters
d.constants()['main/sigma'] = 5.0

# Run the simulation
s.run()

# Access the simulation's results
r = s.results()

# Time points
t = r.points()

# Individual variables
x = r.states()['main/x']

# Output results
print(t.values()[0:20])
print(x.values()[0:20])
```
and then run it with:
```
./build/OpenCOR.app/Contents/MacOS/OpenCOR -c Python python/test.py
``` 

All going well, the output should be:
```
[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19]
[1.         1.0063807  1.02510889 1.05570799 1.0978784  1.15148222
 1.2165323  1.2931827  1.38172157 1.48256562 1.59625602 1.72345557
 1.86494655 2.02162929 2.19452084 2.38475334 2.59357164 2.82232947
 3.0724832  3.34558244]
```

**Comment by dbrnz** [comment]
Or for that matter, we can open a local CellML/SEDML file with:
```
s = oc.openSimulation('path/to/file')
```

**Comment by agarny** [comment]
> Or for that matter, we can open a local CellML/SEDML file with:
> 
> ```
> s = oc.openSimulation('path/to/file')
> ```

Yes, that's what I was going to suggest after reading your original message. This aside, I agree that it's the way we should test simulation code.

**Comment by agarny** [comment]
Otherwise, not `Improvement` but `Task` since this has nothing to do with OpenCOR itself. It's more about our infrastructure.

**Comment by agarny** [comment]
FTR, to run a DAE model (i.e. a model that requires an NLA solver) without the GUI (e.g. using a Python script) and on Windows results in a couple of message like this:

![Image2](https://user-images.githubusercontent.com/602265/70673792-aab1f080-1ce8-11ea-9e2f-e0bfa7a6fcb8.png)

Interestingly enough, we don't get such messages on either Linux or macOS...!?

Anyway, the problem is that we need to track the NLA solver that is to be used by a given runtime and we do this by calling [`Solver::setNlaSolver()`](https://github.com/opencor/opencor/blob/9f90a3b165cda3ae808c3b63bef8231bfe74ef25/src/plugins/solverinterface.cpp#L149-L155) (and then [`Solver::unsetNlaSolver()`](https://github.com/opencor/opencor/blob/9f90a3b165cda3ae808c3b63bef8231bfe74ef25/src/plugins/solverinterface.cpp#L159-L164)). As can be seen, this sets a property on `qApp`, which is then used when needing to do a non-linear solve (by calling [`Solver:: doNonLinearSolve()`](https://github.com/opencor/opencor/blob/9f90a3b165cda3ae808c3b63bef8231bfe74ef25/src/plugins/solverinterface.cpp#L32-L47)). So, the solution is not to set the property on `qApp`, but on the runtime instead. This means that we won't need [`Solver::unsetNlaSolver()`](https://github.com/opencor/opencor/blob/9f90a3b165cda3ae808c3b63bef8231bfe74ef25/src/plugins/solverinterface.cpp#L159-L164) anymore.

**Comment by agarny** [comment]
Argh, although commit 370c593 is a slight improvement over what we had before (using the runtime rather than `qApp`), it doesn't actually prevent the above message on Windows! (FWIW, we only get one message now since we don't have `Solver::unsetNlaSolver()` anymore.

**Comment by agarny** [comment]
Ok, FWIW, the problem was really with `QObject::setProperty()`, which doesn't play well for us on Windows with no GUI. So, instead, we now use `QObject::setObjectName()` (!!) to keep track of a runtime's NLA solver...

**Comment by agarny** [comment]
Ok, very interestingly (and super annoyingly), to be able to run our Python-based tests on our different platforms, we would need to use one significant digit for our test results. This is clearly ridiculous, so instead we distinguish results based on the platform on which they are run. Not only that, but also on whether they are run using the release or debug version of OpenCOR. And... still not only that, but also using the test results on Windows release using our CI machine since the test results are different on my Windows VM! This should hopefully get PR #2255 to finally succeed!

**Comment by dbrnz** [comment]
Are the differences also there when the various simulations are run manually in the GUI (i.e. without any Python code), visible by say exporting result sets as CSV?

**Comment by agarny** [comment]
I haven't checked, but I will as part of issue #2254. Still, my gut feeling is that there are also there. Might check that tomorrow.
