### ISSUE TITLE
Very high memory usage when loading a model

### ISSUE THREAD

**Issue by massimiliano-leoni** [opencor/opencor#2279]
I just tried to open a very complex model file, the text file weights around 3 MB.
OpenCOR allocates almost 19GB or memory when opening that file. After the loading is done, it deallocates most of it.

The issue is that most computers, including mine, don't have 19 GB of memory, which in any case sounds like too much. Is it possible to mitigate this behaviour?

**Comment by agarny** [comment]
Hi @massimiliano-leoni, I agree that to need 19GB of RAM to process a 3MB-big CellML file is ridiculous. However, remember that OpenCOR currently relies on the CellML API (i.e. not libCellML) and it is known to require quite a bit of memory to do its things.

So, right now, I would say that the culprit is the CellML API and that there is nothing we can do about it until we move to libCellML. This being said, I am more than happy to double check that the CellML API is indeed the culprit. So, it would be great if you could share your model, be it publically or privately. (I will then also check using libCellML directly.)

**Comment by massimiliano-leoni** [comment]
Hi Alan, thanks for the quick reply. I will send you the file via email so you can inspect it.

**Comment by agarny** [comment]
This has been addressed in issue #2284, so closing.
