### ISSUE TITLE
Bug retrieving HTML instead of CellML

### ISSUE THREAD

**Issue by mirams** [opencor/opencor#2373]
This may be a PMR rather than OpenCOR issue, not sure! 

I clicked in the top left to retrieve a Grandi 2011 atrial model from the repo and it tried to open and parse an HTML page as CellML:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/858776/89664438-17f54000-d8cf-11ea-9e3f-413d068fcefb.png">

**Comment by agarny** [comment]
Hi Gary, I can indeed confirm the issue and, looking at the URL for the Grandi 2011 model (https://models.physiomeproject.org/workspace/595/rawfile/dce05193451a275f2a8778d607b2d6456b548e3e/grandi_2011_atrial_with_meta.cellml), it looks good.

However, if you are [not logged in PMR](https://models.physiomeproject.org/login) and then click on the above link then you will see that you are asked to log in. (What you see in OpenCOR is the HTML code for that log in page.)

On ther other hand, if you click on the link for the Grandi 2010 model (https://models.physiomeproject.org/workspace/grandi_pasqualini_bers_2010/rawfile/8a2c891da5f2f1b90d9c465b7bc63f652999d096/grandi_pasqualini_bers_2010.cellml) then you can see that you don't need to be logged in to see its contents (hence it all works fine in OpenCOR).

So, although PMR allows OpenCOR to list the Grandi 2011 model (because there is a public exposure for it), one needs to be logged in PMR to see its contents (while it's all fine with the Grandi 2010 model)...!?

@metatoaster and @nickerso: is that "normal"?

**Comment by metatoaster** [comment]
Looks like an exposure was approved for publication but then the workspace was kept private.  This should not be the case, as the workspace would also need to be made public.  There is nothing to enforce this but given that the original submitter requested that the data be made public anyway, I have also made the workspace associated with the exposure public so that the model file may now be retrieved.

**Comment by agarny** [comment]
Great, thanks a lot @metatoaster, I can confirm that everything works fine from OpenCOR.

Gary, note that the model contains a non-top-level piecewise statement, which means that the `CellML Text` view won't work with it (something that got "inherited" from COR and that will be addressed at some point -- sorry!), but you can run in the `Simulation Experiment` view just fine.

**Comment by mirams** [comment]
Thanks for the quick investigation and fix everyone 🙂👍
