### ISSUE TITLE
Simulation Experiment view: cannot export a CellML 1.1 model to a COMBINE archive on Windows

### ISSUE THREAD

**Issue by WeiweiAi** [opencor/opencor#2478]
The repository link is https://models.physiomeproject.org/workspace/666
When I exported COMBINE Archive (voltage_clamp_activation_experiment.cellml) using OpenCOR, I got the error like the attached snapshot
![image](https://user-images.githubusercontent.com/14898803/118563013-e7c5c080-b7c1-11eb-9833-644470654897.png)

**Comment by agarny** [comment]
Just tried on macOS, but to no avail. Might be an issue on Windows only.

**Comment by WeiweiAi** [comment]
The version of OpenCOR is snapshot 2021-04-29, Windows 10.
I was able to export COMBINE Archive but unfortunately, I am not sure which version I used. 
I will use the latest 2021-05-05 version to try again.

**Comment by agarny** [comment]
I can confirm the problem on Windows. I reckon it might have to do with the use `/` rather than `\` on Windows. If so, it should be easy to fix. At least, I can reproduce it.

**Comment by agarny** [comment]
FTR, things have been broken since the 2021-04-29 snapshot, as a result of addressing an issue with the XML base in the CellML API (see https://github.com/opencor/opencor/pull/2464). In the present case, the problem is that a file name of a CellML file was `c:/...` while the XML base of the main CellML file was `C:/...` (i.e. lower vs upper case for the drive letter). To create the archive, we need to determine the relative path of a CellML file and we do this by removing the common part of the XML base of the main CellML file, which obviously failed. The solution is therefore to use `Qt::CaseInsensitive` when calling `QString::remove()`.
