### ISSUE TITLE
Errors reported on wrong line

### ISSUE THREAD

**Issue by MichaelClerx** [opencor/opencor#2606]
On snapshot 2021-10-05

The attached file [old.zip](https://github.com/opencor/opencor/files/7954198/old.zip) has some errors* starting on line 119, but OpenCOR reports an issue on line 111

![Screenshot from 2022-01-27 22-22-29](https://user-images.githubusercontent.com/517644/151453602-b8f3945b-6660-4236-8634-4438e452cf0b.png)

Just to verify in another editor that the issue is on line 119:

![Screenshot from 2022-01-27 22-22-20](https://user-images.githubusercontent.com/517644/151453614-c7bf53fc-88f5-43ac-b422-deb132198eec.png)

*There's a space in front of the initial value. Can't remember if this is technically an error

**Comment by agarny** [comment]
I think that the space makes the initial value a string rather than a number. If that's the case then the first issue is at line 115 and not line 111 (or even line 119). So, yes, OpenCOR reports the wrong line number. Well, it's not OpenCOR's fault, but that of the CellML API (or libxml2 or whatever is used to determine line/column numbers internally). Now, once again, because we are moving to libCellML, we are not going to "waste" time fixing the CellML API. Sorry! 😕
