### ISSUE TITLE
Method in tutorial is `voi_and_variables` rather than `voiAndVariables`

### ISSUE THREAD

**Issue by jonrkarr** [opencor/opencor#2611]
(I'm not sure which GitHub repository this corresponds to, if any. Thus, I'm posting this here.)

The page below of the tutorial discusses a Python method `voiAndVariables`. The name of this method is `voi_and_variables`.
https://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/opencor_python.html

**Comment by agarny** [comment]
Thanks, @jonrkarr, this is an old tutorial which is not officially part of OpenCOR (so closing your issue) and, indeed, it hasn't been updated to account for the fact that the methods have been renamed to make them more Pythonic.

@nickerso, any idea of who is in charge of that tutorial and whether it's still maintained?

**Comment by nickerso** [comment]
This is the tutorial source: https://github.com/ABI-Tutorials/CellML-OpenCOR-PMR. Its kinda been left unchanged for a while as we haven't run the DTP since before COVID and that was the motivating driver for "recent" updates. I've just made https://github.com/ABI-Tutorials/DTP-CompPhys/issues/10 to track this one, thanks @jonrkarr .
