### ISSUE TITLE
Interface bug:  blank tab header

### ISSUE THREAD

**Issue by gbernardino** [opencor/opencor#2698]
I am using OpenCOR version 0.6 in macOs 10.16, and the headers of the selected tabs are seen in blank when OpenCOR is the active app. Weirdly, when the focus is somewhere else (i.e. when I open the preferences dialog). I attach some examples:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/6797235/200180640-e56ebc91-8383-4de4-b704-876ba601c3d8.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/6797235/200180768-0ffe685e-3784-44bc-8a5c-5eed08329e33.png">

The tab is correctly seen when the focus is in the preferences.
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6797235/200180829-e1c24419-765b-414f-883c-dae33b58e589.png">

**Comment by agarny** [comment]
Hi @gbernardino, OpenCOR 0.6 is quite old and macOS has changed quite a bit since. May I suggest that you try the [latest snapshot](https://opencor.ws/downloads/index.html) (the one from 31 May 2022) and let us know how it works for you? For what it is worth, we should be releasing OpenCOR 0.7 in the next few weeks.

**Comment by gbernardino** [comment]
Yes, it worked, thanks!

**Comment by agarny** [comment]
> Yes, it worked, thanks!

Great and thanks for closing the issue.
