### ISSUE TITLE
"The code could not be compiled" error when there are incompatible units. 

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2739]
When the unit for a variable in the main computational environment is defined differently to how it is defined in the module, I get a "the code could not be compiled" error. 

The error message should let the user know which variable has unit inconsistencies. Otherwise, debugging large models is painful. 

Simple reduced example here with variable Caz. units milliM in the environment (SN_to_cAMP.cellml) and dimensionless in the module (SN_to_cAMP_modules.cellml).
[SN_to_cAMP.zip](https://github.com/opencor/opencor/files/13328390/SN_to_cAMP.zip)

**Comment by agarny** [comment]
Thanks @FinbarArgus. As you know, OpenCOR is going to use libOpenCOR in the background, which itself uses libCellML. So, if anything, it's best to check what libCellML says / does about your model. So, I thought I would give it a try and... well, your model crashes libCellML!

Anyway, your original issue is going to be addressed in libOpenCOR, so I am closing this GitHub issue and creating one in libCellML since your model should never crash libCellML in the first place (see https://github.com/cellml/libcellml/issues/1203).
