### ISSUE TITLE
MathML Viewer widget: Should underscore result in a subscript?

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2744]
An underscore character in a variable's name is interpreted as a subscript operator when rendering the name in OpenCOR's maths display; indeed `A_b` in maths mode in LaTeX means "A<sub>b</sub>". This though causes display issues with names such as `dot_a_of_q_1_c` or even `my_variable` (which presumably is not intended to read as "my<sub>variable</sub>"). Is this "feature" documented as such? The help pages for the CellMLTextView plugin make no mention of this implicit subscript operator.

From the CellML 2.0 specification, an identifier::
```
SHALL consist of a single Basic Latin alphabetical character, which MAY be followed by any combination
of Basic Latin alphanumerical characters and/or Basic Latin underscores.
```
and hence variable names might have any number or underscore characters in them.

Why not consider a CellML identifier as a sequence of characters, with **NO** implicit convention as to how any embedded underscores affect the display in OpenCOR's maths view? And then allow (via metadata) for an identifier to have an associated display form to use in a graphical display (e.g. an SVG image or even LaTeX markup)?? This would also resolve #2738.

**Comment by agarny** [comment]
Is this "feature" documented as such? The help pages for the CellMLTextView plugin make no mention of this implicit subscript operator.

It's not mentioned in the [`CellMLTextView Plugin` page](https://opencor.ws/user/plugins/editing/cellmlTextView.html#:~:text=the%20view%20has%20the%20same%20features%20as%20the%20Raw%20CellML%20view), but it is mentioned in the [`RawCellMLView plugin` page](https://opencor.ws/user/plugins/editing/rawCellmlView.html#plugins-editing-rawcellmlview:~:text=The%20equation%20viewer%20can%20be%20customised%20using%20its%20context%20menu%3A) which features are also available in the `CellMLTextView Plugin` page.

So, as you can see, underscores are, by default, used to specify subscripts, but the user can disable that feature (and it will be remembered from one session to another).

> Why not consider a CellML identifier as a sequence of characters, with **NO** implicit convention as to how any embedded underscores affect the display in OpenCOR's maths view? And then allow (via metadata) for an identifier to have an associated display form to use in a graphical display (e.g. an SVG image or even LaTeX markup)?? This would also resolve #2738.

I can see two issues with this approach:
1. This would break the current behaviour whereby people rely on the current feature to render variable names with subscripts (e.g., `V_m`, `i_Na`, `i_K`, etc. are used a lot in CellML); and
2. Where would you store that metadata? In a separate file as we (should) do when annotating variables? Or it could be done directly in the CellML file and, when it comes to the CellML Text view, we could have something like this:
```
var i_Na: microA_per_cm2 {pub: in, rend: xxx};
```
with `xxx` the way we would like `i_Na` to be rendered. But then, where would an image be stored? Also, to use LaTeX markup would require converting that markup to presentation MathML (since this is what our MathML Viewer widget uses to render an equation).

Hmm, I need to think about this more...

**Comment by dbrnz** [comment]
> I can see two issues with this approach:

> This would break the current behaviour whereby people rely on the current feature to render variable names with subscripts (e.g., V_m, i_Na, i_K, etc. are used a lot in CellML);

This could be the fallback -- if no alternative rendering is given then use current behaviour.

>  Where would you store that metadata? In a separate file as we (should) do when annotating variables? Or it could be done directly in the CellML file

Is not a `<rdf:RDF>...</rdf:RDF>` block the place to put this? Variables would require a `cmeta:id` which is referenced by RDF. The ideal would be to allow Turtle to be somehow embedded, as it's a much, much cleaner why to make RDF statements -- I've managed to do so in SVG with `<metadata data-content-type="text/turtle"><![CDATA[ ... ]]/>` -- could we get away with something similar in CellML without breaking the language specification?

One way to store SVG is as data URLs, e.g. `data:image/svg+xml;base64,...`, although I'm include to use a mimetype such as `application/x-latex` to identify a string literal as containing LaTeX, and then render it when needed.

**Comment by agarny** [comment]
> Is not a `<rdf:RDF>...</rdf:RDF>` block the place to put this? Variables would require a `cmeta:id` which is referenced by RDF.

Yes, it would be, but annotations in CellML (and in other COMBINE-related standards) should nowadays be done in a separate file. That's the way annotation has been agreed by the COMBINE community a few years ago (see [here](https://academic.oup.com/bib/article/20/2/540/5164345#:~:text=of%20semantic%20annotations.-,Store%20annotations%20in%20a%20separate%20file,-This%20practice%20will)).

> The ideal would be to allow Turtle to be somehow embedded, as it's a much, much cleaner why to make RDF statements -- I've managed to do so in SVG with `<metadata data-content-type="text/turtle"><![CDATA[ ... ]]/>` -- could we get away with something similar in CellML without breaking the language specification?

Because annotation should nowadays be done in a separate file, it means that we can use Turtle or something else (see [here](https://academic.oup.com/bib/article/20/2/540/5164345#:~:text=An%20additional%20advantage%20of%20storing%20annotations%20in%20a%20separate%20file%20is%20that%20the%20RDF%20content%20can%20be%20serialized%20in%20various%20formats%20including%20XML%20or%20Turtle%2C%20whereas%20currently%20the%20serialization%20is%20dictated%20by%20the%20model%20format.)).

> One way to store SVG is as data URLs, e.g. `data:image/svg+xml;base64,...`, although I'm include to use a mimetype such as `application/x-latex` to identify a string literal as containing LaTeX, and then render it when needed.

Agreed about storing an SVG, but I am not sure whether I want to support SVG for the rendering of a variable in an equation. I mean, this would require providing a way to specify an SVG file in the Raw CellML and CellML Text views.

So, leaving SVG aside (for now? in fact, could you provide me with a use case?) and "ignoring" best practices for annotations, maybe we could do something like this:

- Use the current behaviour for something like:
```xml
<variable name="A_my_superscript_my_subscript" initial_value="10" units="dimensionless"/>
```
- Use the `rendering` LaTeX-based annotation for something like:
```xml
<variable name="A_my_superscript_my_subscript" initial_value="10" units="dimensionless">
  <rendering xmlns="http://www.opencor.ws/">
    A^{my\_superscript}_{my\_subscript}
  </rendering>
</variable>
```

In the CellML Text view, we could have that rendering information expressed as follows:
```
A_my_superscript_my_subscript: dimensionless {init: 10} rendered as A^{my\_superscript}_{my\_subscript};
```

I was originally thinking of having that piece of information in `{init: 10, rend: ...}`, but curly brackets would make it confusing.

**Comment by dbrnz** [comment]
> Because annotation should nowadays be done in a separate file, it means that we can use Turtle or something else (see [here](https://academic.oup.com/bib/article/20/2/540/5164345#:~:text=An%20additional%20advantage%20of%20storing%20annotations%20in%20a%20separate%20file%20is%20that%20the%20RDF%20content%20can%20be%20serialized%20in%20various%20formats%20including%20XML%20or%20Turtle%2C%20whereas%20currently%20the%20serialization%20is%20dictated%20by%20the%20model%20format.)).

There's annotation and annotation... The linked paper is about `semantic metadata`, and I agree with its recommendations; what I'm proposing here is metadata describing how a variable should be presented (or rendered) when viewed by a user. To me, this information is `metadata` or `annotation` since it is additional to the meaning a variable has in the mathematical expression that it is part of.

> So, leaving SVG aside (for now? in fact, could you provide me with a use case?) and "ignoring" best practices for annotations, maybe we could do something like this:

I was thinking SVG since it is a scalable way to encode a visual representation, and my editor can easily output SVG (but just as easily LaTeX, so let's stick with that).

Yes, I like the `<rendering/>` tag -- what about it having a `type` attribute? Initially it would be `application/x-latex`, but this allows for other (future) ways in which rendering might be specified.

**Comment by agarny** [comment]
> Yes, I like the `<rendering/>` tag -- what about it having a `type` attribute? Initially it would be `application/x-latex`, but this allows for other (future) ways in which rendering might be specified.

Ok for the `rendering` tag then. Regarding the `type` attribute, maybe it would be best to wait until we actually need it, if ever? Should it ever be needed, it could become an optional attribute and, if not present, it would imply `application/x-latex`.

**Comment by agarny** [comment]
Closing in favour of #2738.
