### ISSUE TITLE
Constant gets overwritten in Matlab code export

### ISSUE THREAD

**Issue by dbmri** [opencor/opencor#2793]
Hello,

I'm trying to modify an existing CellML model, and zero out certain equations to see the effect.

Upon exporting the code to Matlab, however, it seems that a constant value (constant 125) is overwritten when making a certain modification.
![matlabError](https://github.com/opencor/opencor/assets/141261295/80ee768f-09a9-43c2-8b46-7bc02cb28756)

This error is not present in the Python or C exported code. It seems like in Python and C, a new constant is created, which seems like the correct behavior:
![python](https://github.com/opencor/opencor/assets/141261295/7db355ad-b070-4fb0-b5bc-20ce87e32a2c)
![c](https://github.com/opencor/opencor/assets/141261295/fe253652-49c5-4b6c-b719-4ce3a95ffbe5)
(in C and python it's constant 124, I assume because of the 1 vs. 0 based indexing; and the total number of constants in C and Python would then be 129 vs. 128 in Matlab).

The original CellML model has an equation that looks like this (pseudocode):

y1 = c1 * v1 * (c125 * ...)

which we've modified to zero it out:

y1 = 0{dimensionless} * c1 * v1 * (c125 * ...)

and it behaves as expected.

Then, in a totally separate equation, I've set

ode(y2, t) = 0 {dimensionless};

I've made other similar modifications, but this particular one seems to trigger a corner case in the Matlab exporter.

Instead of creating a new zero constant, it overwrites the previous value of c125 (see screenshot in the Matlab code).

This doesn't seem to affect the results directly, since c125 is effectively zeroed out anyway in the modified version of y1; but it does seem to demonstrate some inconsistency in the Matlab exporter that is not present in the Python or C exporters.

Unfortunately since this is work in progress and not yet published, I'm not able to share the source files at this point in time.

**Comment by agarny** [comment]
Hi, this is a behaviour that we have also observed, unfortunately. We never looked into fixing it because it's part of the [CellML API](https://cellml-api.sourceforge.net/), a legacy library that OpenCOR uses to handle CellML files. It's not being officially maintained anymore. I did fix a few issues with it since it did crash OpenCOR in some cases (!!), but I never looked into fixing the MATLAB export (see below).

In OpenCOR 0.7.x, the export to C, FORTRAN 77, MATLAB, and Python is done internally, but in OpenCOR 0.6, it's done using a user-defined format such as [this one](https://github.com/user-attachments/files/16067863/MATLAB.txt) for MATLAB (the extension of the file was changed from `.xml` to `.txt` since `.xml` is not allowed by GitHub). So... if you are keen, you could use OpenCOR 0.6 to export your model to MATLAB, and tweak that `MATLAB.xml` file yourself. I am not aware of any documentation for that format, so I really can't help you here. Sorry!

Alternatively, you might want to look into [libCellML](https://libcellml.org/) (our new CellML API). It primarily supports [CellML 2.0](https://www.cellml.org/cellml/2.0), but it can also be used to import CellML 1.0/1.1 models. More importantly, it's much more robust than the CellML API used in OpenCOR and is what we will be using in a future revamped version of OpenCOR. libCellML comes with a code generator facility which relies on a generator profile to customise code generation. This is how, by default, libCellML can convert a CellML model to C and Python. However, it should be possible to write a similar generator profile for MATLAB. Needless to say that if you were to go down that route then we would gladly welcome a [pull request](https://github.com/cellml/libcellml/pulls) from you.

So, yes, sorry that I can't be of more direct help but hopefully one of the two aforementioned options is going to work for you...

**Comment by agarny** [comment]
I am closing this issue since this will sadly never be fixed. For me, the way forward is to move to libCellML and write a generator profile for MATLAB.
