### ISSUE TITLE
Python: include the ability to easily release all values at once

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2801]
Add a simulation.release_all_values() that releases all states and algebraic variables so that it can be simply called with/after simulation.clear_results() to reset all memory.

This follows on from the memory fix of https://github.com/opencor/opencor/issues/2798 , which requires the user to keep track of the variables and variable names that need to be reset. Not having to keep track of these on the user side would make things easier.

**Comment by agarny** [comment]
@FinbarArgus, we originally had:
- `DataStoreVariable.values()`; and
- `DataStoreVariable.release_values()`.

But now, we have:
- `DataStoreVariable.values()`;
- `Simulation.release_values()`; and
- `Simulation.release_all_values()`.

In other words, to obtain some values is done from a `DataStoreVariable` object (no way around that) while to release preobtained values is done from a `Simulation` object (so that all the clearings, releasings, etc. is always done from a `Simulation` object, which I agree is more convenient).

I imagine that in your case you will most likely call `Simulation.release_all_values()`, but it doesn't harm still having the `release_values()` method. Note, if an end-user doesn't release the values s/he previously retrieved then those values will be automatically deleted when a `Simulation` object gets deleted. This is slightly better to what we had before since before those values were automatically deleted after having executed a Python script. The difference is due to the fact that values are now tracked by the corresponding `Simulation` object.

Is that all fine with you? If so then I am going to wrap things up, merge the corresponding PR, and then release a new snapshot.

**Comment by FinbarArgus** [comment]
Cool, I will test this and incorporate it into Circulatory_Autogen as soon as I figure out how to install libraries after the changes in #2800

**Comment by FinbarArgus** [comment]
Awesome! First quick test the memory leak is about 750 times smaller. From 3Mb per simulation to 4kb per simulation. This should be negligible for anything we are using Circulatory Autogen for now.

**Comment by agarny** [comment]
> Awesome! First quick test the memory leak is about 750 times smaller. From 3Mb per simulation to 4kb per simulation. This should be negligible for anything we are using Circulatory Autogen for now.

Great and thanks for the feedback!
