### ISSUE TITLE
WSL2Ubuntu instance of OpenCOR : Issue with invisible Graph

### ISSUE THREAD

**Issue by DrVeeCee** [opencor/opencor#2820]
The OpenCOR instance on my machine runs on the Windows SubSystem as Linux (WSL2) Ubuntu.
I am using help from the tutorial's webpage to learn and run some standard simulations. 
[(https://www.cellml.org/getting-started/tutorials#:~:text=CellML%20Tutorials%201%20VPH%20tools%20tutorial%20at%20EMBC,Modular%20modelling%20with%20CellML%201.1%20...%20More%20items)]
However, I am unable to view the graph.
According to the tutorial, it should look like this: [https://www.cellml.org/getting-started/tutorials/opencordemo], but in reality, it looks like this : (see attachment)  
![image](https://github.com/user-attachments/assets/6579dff0-f038-48c4-8eb4-b1b3997cbfff)

Please comment.
Vinamra

**Comment by agarny** [comment]
Hi Vinamra, may I ask why you are running the Linux version of OpenCOR on Windows under WSL2?

OpenCOR was never meant to be used like this. We have a Windows, Linux, and macOS version of OpenCOR and each version is meant to be used on the corresponding system (hence closing your issue). You are using Windows, so I would definitely recommend using the Windows version of OpenCOR.

Still, looking at your screenshot, it looks like there might be some rendering issues when running OpenCOR the way you are. You might therefore want to reset all of OpenCOR. With a bit of luck, it might get you back on track:
- Go to the `Tools` menu;
- Click on the `Reset All` menu item; and
- Click on the `Yes` button.

**Comment by agarny** [comment]
Hi Vinamra,

Nothing wrong with using WSL2, it's just that when it comes to OpenCOR, it's better to use the Windows version since that's the operating system you are using.

Anyway, good to see that the Windows version of OpenCOR is working fine for you. Otherwise, I can see that you have a small screen resolution, so you might be interested to know that you show/hide the docked windows by:
- clicking on the `View` menu; and
- clicking on the `Docked Windows` menu item.

This will give more space for the `Simulation Experiment` view.

**Comment by agarny** [comment]
I forgot to comment on the documentation you are using. This is some very old documentation. Please have a look at https://opencor.ws/user/ and https://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/index.html.

**Comment by DrVeeCee** [comment]
Bingo!
