### ISSUE TITLE
Qt 5.4: OpenSSL: address issue of some methods not being resolved

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#516]
Since upgrading to Qt 5.4 (see issue #513), we are now getting OpenSSL messages on Linux and OS X. On Linux:

```
QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv2_server_method
```

On OS X:

```
QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
QSslSocket: cannot resolve SSL_select_next_proto
QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
QSslSocket: cannot call unresolved function SSL_get0_next_proto_negotiated
```

Now, those are just warnings and they don't actually affect the good functioning of OpenCOR. Still, if we run the GUI version of OpenCOR from the command line, we will see those messages if the ```CellML Model Repository``` window is visible.

**Comment by webmaster128** [comment]
The issues on OS X exist because Apple still ships OpenSSL 0.9.x in OS X 10.10. OpenSSL 0.9 does not support TLS 1.1 and TLS 1.2 is not officially supported by Qt anymore. To get rid of the problem, you need to ship a version of OpenSSL with you application on OS X.

**Comment by agarny** [comment]
Thanks Simon, you are confirming what I thought might have been the case. In fact, I already do something like that for Windows. I just wish I didn't have to do the same for OS X. Anyway, my understanding is that Qt 5.4.1 should soon be released, so that might be good enough for me (my application only access SSL resources that I know and trust).

**Comment by webmaster128** [comment]
I am glad I could add some insights. I came across this post because we're dealing with the same issue. AFAIK you can ignore the messages for now but keep in mind:

> From Qt version 5.2 onwards, the officially supported version for OpenSSL is 1.0.0 or later. Versions >= 0.9.7 and < 1.0.0 might work, but are not guaranteed to.

http://doc.qt.io/qt-5/build-sources.html

I think a good workaround would be to suppress the warnings in release versions and still have it on in debug versions. Because otherwise you might suppress and miss more serious OpenSSL warnings.

**Comment by agarny** [comment]
Agreed, OpenSSL warnings should only be suppressed in release mode.

**Comment by webmaster128** [comment]
Let me share another insight, we just discovered at Kullo: The reason you are getting the errors 
```
QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv2_server_method
```
is that Debian patched SSL2 out of OpenSSL because it is not secure anymore. This has been done back in 2011 (or earlier) in the Debian packages of OpenSSL 1.0.x.

The official OpenSSL library does not remove SSL2 before OpenSSL 1.1.x

> SSLv2_method, SSLv2_server_method and SSLv2_client_method where removed in OpenSSL 1.1.0.

https://www.openssl.org/docs/ssl/SSL_CTX_new.html

That can be confirmed on a current Fedora, where you have unpatched up-to-date OpenSSL 1.0.x. So you can basically say that this a Debian problem.

**Comment by agarny** [comment]
Thanks for the additional information, Simon.

My Linux box runs Ubuntu, but for all I know they might be using the same version of OpenSSL 1.0.x as Debian. I might have a quick look at Fedora tomorrow, just to see.

Anyway, if I understand you correctly, to avoid the warnings, one either has to disable them (which will soon be possible using Qt 5.4.1 and above) or ship an official, i.e. unpatched, copy of OpenSSL 1.0.x (but not OpenSSL 1.1.x) along with one's application. Is that correct?

**Comment by webmaster128** [comment]
Jap, correct. But in case of the given SSL2 warnings, I think it is ok to suppress them.
