### ISSUE TITLE
Single Cell view: rename it to something more appropriate?

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#567]
The name "Single Cell" is quite confusing and really has nothing to do with the purpose of the view. A possible name might be "Model Simulation".

**Comment by nickerso** [comment]
I should add that this is not meant to be something done any time soon, just flagging it as something to consider one rainy day in the future...

**Comment by agarny** [comment]
I agree that the name is not that great. However, at some point, I would like to be able to run (simple) multi-cellular simuations in OpenCOR, hence the name of ```Single Cell``` for the current simulation view.

Otherwise, to have ```Model Simulation``` as a name for the view would be slightly redundant since that view is part of the ```Simulation``` mode.

**Comment by agarny** [comment]
Duplicate of issue #1256, so closing.
