### ISSUE TITLE
Possible bug using CVODE in opencor for stiff DAEs

### ISSUE THREAD

**Issue by vraj004** [opencor/opencor#569]
I have been having trouble with integrating a stiff DAE using CVODE in opencor. I find that the legacy software, opencell, behaves more predictably. I can provide the cellml file.

**Comment by agarny** [comment]
It would indeed be good if you could provide the CellML file (maybe you could make it available on the CellML Repository and then give the link to the workspace?).

Otherwise, yes, OpenCOR is not yet on par with OpenCell when it comes to DAE models (e.g. see issues #188, #536 and #537). We are hoping to address that shortcoming not in the forthcoming version of OpenCOR (v0.4), but the next one (v0.5).

**Comment by vraj004** [comment]
I think this is actually not a bug now - at least for my example.

**Comment by agarny** [comment]
Ok, closing it then.
