### ISSUE TITLE
PMR window: allow a workspace to be cloned

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#593]
The idea is really to 'force' people to use PMR through OpenCOR and this can be done by making it easy for the user to clone a given workspace from within OpenCOR. (This obviously requires Git to be installed on the user's computer.)

**Comment by nickerso** [comment]
Rather than 'forcing' users to make use of PMR, this should be seen as encouraging users to form better habits and adopt workflows that better support reproducible and open science.

Ideally, OpenCOR would make use of git internally and not require users to install git separately. The use of Git behind the scenes can then be abstracted from the user, who generally shouldn't need to be concerned with the details. This would be similar to the way @hsorby is proving access to PMR workspaces in the MAP client (I think). This obviously only works for the straightforward case where merging, branching, etc is not required, but that is the most common case anyway.

**Comment by agarny** [comment]
I do intend to have OpenCOR making use of git internally, so I think we are on the same wavelength here. However, are you saying that part of the OpenCOR installation process (or compressed file) should be to install (contain) an internal (to OpenCOR) copy of git? I.e. something similar to what OpenCell used to do with gcc? Is that really what we want? (I have just checked my copy of git on Windows and it's ~255 MB big...)

**Comment by nickerso** [comment]
Its just another dependency like LLVM, Sundials, or Qt, right? Not sure that you need a full git client install though, perhaps something like libgit2 (https://libgit2.github.com/) or similar is all you need. Or maybe just the PMR2 workspace manager directly (https://github.com/PMR2/pmr2.wfctrl).

**Comment by agarny** [comment]
I didn't know about libgit2, but it looks like it might be the way to go, so thanks for that (it would, indeed, be similar to using LLVM and the other third-party libraries used by OpenCOR (it's different for Qt)).

**Comment by agarny** [comment]
FWIW, we can now clone a (hard-coded) CellML workspace (Noble 1962) using ```libgit2```. Now, we need to make that approach generic...
