### ISSUE TITLE
Single Cell view: annotating curves

### ISSUE THREAD

**Issue by mpnash** [opencor/opencor#633]
Would be nice to annotate each curve on a graph with the variable name being plotted (e.g. in a user movable legend?).  Also the use of different colours, or line styles for different curves on a single graph would help. 
(Sorry if duplicate request).

**Comment by agarny** [comment]
The second part is indeed a duplicate (see issue #591). Otherwise, once issue #591 is implemented, I imagine there should be no need for being able to annotate curves since that information will be available in the ```Graphs``` pane:

![screen shot 2015-05-29 at 14 44 26](https://cloud.githubusercontent.com/assets/602265/7882788/6a51a1c2-0611-11e5-8a42-0994e243b03f.png)

So, closing this issue. For now, at least.
