### ISSUE TITLE
Single Cell view: use better colours/symbols in the "Parameters" window?

### ISSUE THREAD

**Issue by mpnash** [opencor/opencor#634]
The colours/symbols in the "Parameters" window are rather similar. 
Also the symbols with/without 'holes' look like radio buttons. Consider different shaped symbols?

**Comment by agarny** [comment]
The colours are rather similar? Otherwise, I agree about the symbols being rather similar.

Regarding parameters with a 'hole', the idea is to give a 'hint' that they are different in the sense that they can be edited.

Anyway, I agree that the symbols could be improved. However, my artistic skills being pretty much nonexistent, someone else will have to come up with some suggestions (48x48 pixels).

**Comment by mirams** [comment]
I don't think the colours are colourblind friendly - reds and greens like this are very easy for some people to mix up. This website provides colourblind-friendly colour schemes, and here's a link to one that might work a bit better: http://colorbrewer2.org/?type=qualitative&scheme=Set2&n=3

But I do also find it quite difficult to remember what colour symbol represents what. 

This might be a bit English-centric for you @agarny, but the best I can think of in addition to the colours is perhaps to also shape the icons with a letter:

- 'V' for [state] variable;
- 'A' for Analytic expression (I'd include state variable derivatives in this);
- 'P' for Parameter [or 'C' for Constant, but might look like 'C' for computed expression].

Then to indicate editable-ness just make the uneditable numbers on the right grey instead of black? (or grey background or something?)

**Comment by agarny** [comment]
@mirams, from the [documentation](http://opencor.ws/user/plugins/simulation/SingleCellView.html), you can see that we effectively have four different types of parameters:
![image](https://cloud.githubusercontent.com/assets/602265/16099782/48e3d20a-33ae-11e6-8592-03009adc645d.png)

and I would like those types to remain roughly as is. So, we would need four colours. As for using grey to indicate that something is not editable wouldn't work for me since grey is usually used to mean that something is disabled.

Regarding colours, we could maybe use some of the ones mentioned in this conservative 7-colour palette for colourblind people:
![image](https://cloud.githubusercontent.com/assets/602265/16100153/966ab3a2-33b0-11e6-871d-aab503dc2c34.png)

We could thus keep using blue and red (vermillion), use a bluish green instead of green, and maybe use orange instead of cyan? Then, we could have letters instead of filled/unfilled discs. So, in the end, what about something like (I would clearly have to resize the width of the letters to make them the same width):
![image](https://cloud.githubusercontent.com/assets/602265/16100329/c48cf3a2-33b1-11e6-82b9-c1734cab358e.png)

(For computed constants, we could have a small C within a big C, and maybe dome something similar for the VOI.)

**Comment by agarny** [comment]
Ok, I have come up with the following:
![image](https://cloud.githubusercontent.com/assets/602265/16101079/fadbffb6-33b6-11e6-94f6-713d600f9bb8.png)

**Comment by agarny** [comment]
The problem with the above set of icons is that it kind of gets mixed up with the name of the model parameters. So, here is another set:
![image](https://cloud.githubusercontent.com/assets/602265/16103177/4b9c5df2-33ca-11e6-9c92-6b24b72235de.png)

**Comment by agarny** [comment]
Ok, here is the difference.

BEFORE:
![image](https://cloud.githubusercontent.com/assets/602265/16103469/1e7ddca8-33cd-11e6-952d-e8411d92d9cd.png)

AFTER:
![image](https://cloud.githubusercontent.com/assets/602265/16103509/54ae66b2-33cd-11e6-95ad-c4f31e64c44e.png)

**Comment by agarny** [comment]
I must confess that I am quite happy with the new icons, so I am going to commit my changes and close this issue, but... feel free to reopen it if (really :)) needed...
