### ISSUE TITLE
Single Cell view: error in the initial value of a 'constant' algebraic variable

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#675]
Possibly related to #570. Using OpenCOR Snapshot 2015-06-29 (64-bit) OS X 10.10 (Yosemite).

Came across this "bug" while trying to work out why OpenCOR is giving different solution to some other code I am working on (in OpenCMISS). Given the model (in CellML Text format):

    def model test as
        def comp test as
            var time: dimensionless;
            var v1: dimensionless {init: 0.0};
            var v2: dimensionless;
            ode(v1, time) = 1{dimensionless};
            v2 = sel
                case time < 3{dimensionless}:
                    1{dimensionless};
                otherwise:
                    0{dimensionless};
            endsel;
        enddef;
    enddef;

when I simulate the model I get the expect results (`v1` on top, `v2` below)

![screen shot 2015-07-07 at 11 50 32 am](https://cloud.githubusercontent.com/assets/811244/8535912/6eda98b0-249e-11e5-8156-278122d57d5e.png)

However, when I change `ode(v1, time) = 1{dimensionless};` to `ode(v1, time) = v2;` I get the following anomaly for the initial simulated data point for `v2`:

![screen shot 2015-07-07 at 11 50 01 am](https://cloud.githubusercontent.com/assets/811244/8535931/9d75217c-249e-11e5-91b1-20b0f7e2b395.png)

Obviously I don't expect the time transient of `v2` to change based on how it is used.

OpenCell gives the correct results for both versions of the model, so it is possibly not the CellML API at fault but rather the way the generated code is being used?

**Comment by agarny** [comment]
I can reproduce the issue using the master branch and in 0.4.1, so that's definitely a bug. Sorry about that! I am going to look into it.

**Comment by agarny** [comment]
I just had a look at the C code generated by OpenCOR using the CellML API. For the first version of your sample model, we have:

```
int initializeConstants(double *CONSTANTS, double *RATES, double *STATES)
{
    int ret = 0;
    int *pret = &ret;

#define VOI 0.0
#define ALGEBRAIC 0

STATES[0] = 0;
CONSTANTS[0] = 1.00000;

#undef ALGEBRAIC
#undef VOI

    return ret;
}

int computeComputedConstants(double *CONSTANTS, double *RATES, double *STATES)
{
    int ret = 0;
    int *pret = &ret;

#define VOI 0.0
#define ALGEBRAIC 0

/* Constant v1 */
/* Constant Element with no id */

#undef ALGEBRAIC
#undef VOI

    return ret;
}

int computeOdeRates(double VOI, double *CONSTANTS, double *RATES, double *STATES, double *ALGEBRAIC)
{
    int ret = 0;
    int *pret = &ret;

/* Rate Restore */
RATES[0] = CONSTANTS[0];

    return ret;
}

int computeOdeVariables(double VOI, double *CONSTANTS, double *RATES, double *STATES, double *ALGEBRAIC)
{
    int ret = 0;
    int *pret = &ret;

/* Element with no id */
ALGEBRAIC[0] = (VOI<3.00000 ? 1.00000 : 0.00000);

    return ret;
}
```

while for the second version, we have:

```
int initializeConstants(double *CONSTANTS, double *RATES, double *STATES)
{
    int ret = 0;
    int *pret = &ret;

#define VOI 0.0
#define ALGEBRAIC 0

STATES[0] = 0;

#undef ALGEBRAIC
#undef VOI

    return ret;
}

int computeComputedConstants(double *CONSTANTS, double *RATES, double *STATES)
{
    int ret = 0;
    int *pret = &ret;

#define VOI 0.0
#define ALGEBRAIC 0

/* Constant v1 */

#undef ALGEBRAIC
#undef VOI

    return ret;
}

int computeOdeRates(double VOI, double *CONSTANTS, double *RATES, double *STATES, double *ALGEBRAIC)
{
    int ret = 0;
    int *pret = &ret;

/* Element with no id */
ALGEBRAIC[0] = (VOI<3.00000 ? 1.00000 : 0.00000);
/* Element with no id */
RATES[0] = ALGEBRAIC[0];

    return ret;
}

int computeOdeVariables(double VOI, double *CONSTANTS, double *RATES, double *STATES, double *ALGEBRAIC)
{
    return 0;
}
```

Now, what I didn't expect was ```computeOdeRates()``` to compute what I would (for lack of better word) call 'constant' algebraic variables. Because of that, OpenCOR doesn't call ```computeOdeRates()``` before running a simulation, which explains the output we get for the second version.

So, the fix is to call ```computeOdeRates()``` before running a simulation, except that we don't want the rates to be updated (i.e. we want ```v1'``` to have an initial value of zero), hence we should pass a dummy array for the rates.

**Comment by nickerso** [comment]
Thanks Alan. Just to clarify, since in my example `v2` depends on `time`, it is not a constant variable and therefore does need to be computed in the rates function. Its also not clear to me why you need to use a dummy rates array - there shouldn't be any restriction on `v1'` being zero (and in this example it clearly should not be zero).

It does sound to me like the first output point is being handled differently to the others, and I'm not sure why...

**Comment by agarny** [comment]
Yes, it now makes sense to me why ```v2``` is being computed in ```computeOdeRates()```, and I clearly hadn't thought of that possibility. My bad.

Regarding the dummy rates array, it's purely for aesthetic reasons. Indeed, when you first switch to the Single Cell view (or reset a model), I want to make it 'clear'/'obvious' to the user that the model has yet to be computed, which means ```v1'``` having an 'initial' value of zero.

Now, going back to it, it does indeed look good (to me, at least) from an aesthetic viewpoint, but it looks 'odd' when plotting ```v1'``` (since the very first data point has a value of zero). So, ok, I am going to change that and not use a dummy rates array anymore. Thanks for 'insisting'! :)
