### ISSUE TITLE
List what is new between two consecutive snapshots

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#766]
Currently on the OpenCOR website, the "What is new" page only provides the difference between the latest snapshot and the previous release. This is valuable and useful to have.

I wonder if it would be possible to also provide a separate "tester" page listing the differences between each snapshot as well? It would be useful, at least to me, to be able to see what has changed in the latest snapshot to help decide if I want to update or not.

**Comment by agarny** [comment]
Argh, I knew it was only a matter of time before someone (OK, you! :)) asks me something like this. As it happens, I have been 'contemplating' the idea for some time now. It's just that, at the moment, changes are listed in a [JSON file](https://github.com/opencor/opencor/blob/master/doc/user/whatIsNew.js), so to avoid duplicating information we would only use that file and this is where the problem lies: how to make it such that it can be used both to show differences between the latest snapshot and the latest official version of OpenCOR, as well as changes between the various snapshots.

In the end, I think I am going to leave things as they are. However, in the email I send to the [OpenCOR users mailing list](https://groups.google.com/forum/#!forum/opencor-users), I will now list what is different between the new snapshot and the previous one. (I wanted to do it yesterday, but I was in rush to release the snapshot for @mirams.)

Hopefully, to have those changes listed in the email sent to the mailing list is sufficient, which I think it should be since people really interested in using OpenCOR ought to be subscribed to it (as you are... :)).

**Comment by nickerso** [comment]
Thanks. The changes in the email would be useful and sufficient for those who are on the list, but I think it would still be good to have on the website. One day :)

**Comment by agarny** [comment]
Well, thinking of it, if I put the changes in the email, it means that I will in some way duplicate the information. So, I could create a snapshot-specific field in the aforementioned JSON file to 'list' what has been done.

Ok, so consider it done then. To formally close this issue, I will update the [What Is New?](http://opencor.ws/user/whatIsNew.html) page with information on what has changed between the 2015-09-07 and 2015-09-27 snapshots.
