### ISSUE TITLE
New file menus should always be available

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#805]
Currently the user must be in either the CellML Text or Raw CellML views to access the File->New->CellML model menu items. This is a real pain.

It would be great if the user can create a new CellML model (or SED-ML file?) from any view and that action simply changes the current view of the user to the appropriate view for that type of new file.

**Comment by agarny** [comment]
I can see your point (and I agree with it in principle), but... what would be the appropriate view for a particular type of new file?

Say that you create a new CellML file, should you then be switched to the ```CellML Text``` view, the ```Raw CellML``` view or even the ```Raw``` view?

Also, what happens if the 'appropriate' view isn't available. For example, assuming that the ```CellML Text``` view would be the 'appropriate' view for a CellML file, what if the ```CellML Text``` view is not available (i.e. the user unselected the corresponding plugin)?

**Comment by nickerso** [comment]
> I can see your point (and I agree with it in principle), but... what would be the appropriate view for a particular type of new file?

>Say that you create a new CellML file, should you then be switched to the CellML Text view, the Raw CellML view or even the Raw view?

I think it is pretty obvious which view to choose :) currently you can only create a new CellML file and the CellML Text view is the obvious choice to move the user to, and if they prefer something else it is trivial for them to change to a different view. If you want it to be more flexible, then that would be a preference the user could configure to their liking.

> Also, what happens if the 'appropriate' view isn't available. For example, assuming that the CellML Text view would be the 'appropriate' view for a CellML file, what if the CellML Text view is not available (i.e. the user unselected the corresponding plugin)?

I would like to see a message pop up telling the user what to do if they really want to complete that action. e.g., "you need to enable CellML support if you want to create a new CellML model".

**Comment by agarny** [comment]
> I think it is pretty obvious which view to choose :) currently you can only create a new CellML file and the CellML Text view is the obvious choice to move the user to, and if they prefer something else it is trivial for them to change to a different view. If you want it to be more flexible, then that would be a preference the user could configure to their liking.

Allow me to remind you that OpenCOR relies on a plugin-based approach. So, OpenCOR cannot know that the ```CellML Text``` view is 'better' than the ```Raw CellML``` view when it comes to editing CellML files.

Right now, I can see two options: when the user creates a new file and s/he is not currently using a CellML-based editing view:
 - OpenCOR could display a message box letting the user know that s/he needs to switch to a CellML-based editing view, and list the views available for the user to select one of them (or cancel the action).
 - OpenCOR could switch to the first available CellML-based editing view, i.e. the ```CellML Text``` view (if it is available; since views are 'sorted' alphabetically) or the ```Raw CellML``` view (if it is available and the ```CellML Text``` view isn't).

From your comment above, I guess we might want to go with option number 2?

Otherwise, note that if no CellML-based editing views are available then the user won't be able to create a new CellML file. If on top of that, there is no text-based editing view available (i.e. no ```Raw``` view), then the user won't be able to create any new file at all.

> I would like to see a message pop up telling the user what to do if they really want to complete that action. e.g., "you need to enable CellML support if you want to create a new CellML model".

As mentioned above, if no CellML-based editing view is available, then the ```New``` | ```CellML 1.0 File``` and ```New``` | ```CellML 1.1 File``` menu items won't be available. That's because those menus are part of the ```CoreCellMLEditing``` plugin on which the ```CellML Text``` and ```Raw CellML``` views depend, and which makes it possible to copy/paste, etc., 'render' a mathematical equation, etc.

Then again, maybe those ```New``` | ```CellML 1.0 File``` and ```New``` | ```CellML 1.1 File``` menu items could be handled by the ```CellMLSupport``` plugin. Thus, as soon as there is a CellML-based view (e.g. the ```Single Cell``` view), we will be allowed to create a new CellML file and, if no CellML-based editing view is available, then OpenCOR could display a message similar to the one you mentioned?

**Comment by nickerso** [comment]
> Then again, maybe those New | CellML 1.0 File and New | CellML 1.1 File menu items could be handled by the CellMLSupport plugin. Thus, as soon as there is a CellML-based view (e.g. the Single Cell view), we will be allowed to create a new CellML file and, if no CellML-based editing view is available, then OpenCOR could display a message similar to the one you mentioned?

This would be my preferred approach, although I would go one further and have the `new` menu populated by the core application. This way regardless of what plugins the user has enabled, they will see the full range of capabilities and then be informed as to what they need to do to take advantage of those capabilities.

**Comment by agarny** [comment]
> This would be my preferred approach, although I would go one further and have the ```new``` menu populated by the core application. This way regardless of what plugins the user has enabled, they will see the full range of capabilities and then be informed as to what they need to do to take advantage of those capabilities.

The core application doesn't and shouldn't know anything about what the plugins can or cannot do. That's the whole idea behind having a plugin-based approach.

So, OK, I am going to do it the way I have described it with regards to the ```CellMLSupport``` plugin.

**Comment by agarny** [comment]
FWIW, this is now done (in a branch soon to be merged), although OpenCOR doesn't switch to a 'suitable' view (e.g. the ```CellML Text``` view), should the user be in a non-editable view (e.g. the ```Single Cell``` view). Indeed, when creating a new file from a non-editable view, the view will in some way or another make it clear to the user that nothing can be done in that view, meaning that the user will have 'no choice' but to switch to another view. I think it's better than being automatically switched to a view that may not be the one you are after. Also, we don't have to worry about whether there exists at least one editable view.
