### ISSUE TITLE
Sample tab doesn't appear when built with ENABLE_SAMPLES

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#835]
It does if lines 613 - 618 of `centralwidget.cpp` are commented out...

**Comment by dbrnz** [comment]
The above was a to quick and dirty way to see the samples! Removing `rm ~/Library/Preferences/OpenCOR.plist` does the trick.

**Comment by agarny** [comment]
Hmm, this is odd.

I can't see why it wouldn't appear in the first place and why commenting out lines 613-618 of ```centralwidget.cpp``` would 'fix' it.

I can see deleting (or resetting) ```~/Library/Preferences/OpenCOR.plist``` doing the trick in some cases (hence we can now reset OpenCOR from the command line: ```./OpenCOR -r```), but again I can't see why it would fix things here.

I wish I could reproduce your 'problem' so that I can understand better what is happening. Just to be sure, I manually deleted ```~/Library/Preferences/OpenCOR.plist``` (since ```-r``` will effectively clean it as opposed to delete it), started a version of OpenCOR that was built without the sample plugins and then closed OpenCOR. In other words, I ended up in a state that should be similar to the one you had 'initially'. From there, I started a version of OpenCOR that was built with the sample plugins, and as expected, I can see the ```Sample``` tab. So, yes, I am rather puzzled as how you got your 'problem'...
