### ISSUE TITLE
Data store: add support for BioSignalML

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#841]

**Comment by dbrnz** [comment]
A couple of questions: How many OpenCOR users use the 32-bit version? Are future users likely to require a 32-bit version? OpenCOR currently requires pre-built libraries in seven different flavours (Windows release/debug and 32/64-bit; Linux 32/64-bit; OS/X).

The computing world appears to have embraced the use of 64-bit platforms -- it is now non-trivial to assemble 32-bit versions of the latest releases of the packages and libraries that BioSignalML depends upon.

**Comment by agarny** [comment]
I have just had a look at the OpenCOR downloads since 29 April 2015 (the day OpenCOR 0.4 was released, which corresponds to the first version of OpenCOR that supports Win64; until then, OpenCOR was 'only' released for Win32, Lin32/Lin64 and OSX64). Here are the percentages for the unique downloads of the different versions of OpenCOR 0.4 and 0.4.1, comparing Win32 with Win64 and Lin32 with Lin64 (with the actual number of unique downloads in parentheses):
 - OpenCOR 0.4:
   - Win32 vs. Win64: **26%** (10) *vs.* **74%** (28).
   - Lin32 vs. Lin64: **8%** (1) *vs.* **92%** (11).
 - OpenCOR 0.4.1:
   - Win32 vs. Win64: **24%** (38) *vs.* **76%** (118).
   - Lin32 vs. Lin64: **8%** (2) *vs.* **92%** (24).

So, it looks like we could 'safely' drop the Lin32 version of OpenCOR. Regarding Windows, it seems less obvious. This being said, I wouldn't mind dropping 32-bit versions of OpenCOR altogether.

I don't know if http://store.steampowered.com/hwsurvey is accurate, but if we look at the Windows share, we can see that **87%** of PCs, running Windows, run a 64-bit version of Windows. I am going to mention this (today) in my next OpenCOR report and see what people think. To drop Win32 and Lin32 would certainly make my life much easier (and yours too)!

**Comment by agarny** [comment]
Most of this has been done through PR #853. We now need to make the coding style (and GUI) match that of OpenCOR. Part of it has already been done through PR #854.

**Comment by agarny** [comment]
FWIW, some more 'cleaning up' is to be done through issue #856.

**Comment by agarny** [comment]
Although some more cleaning up is needed, the fact remains that this issue has been addressed, hence closing it.
