### ISSUE TITLE
Use a user's proxy settings

### ISSUE THREAD

**Issue by tactmaster** [opencor/opencor#845]
It would be great it proxy setting could be set, or the system proxy settings could be used. 
I am using Windows 7.
Sadly without internet connection not much can be done with it.

Thanks

Ed

**Comment by agarny** [comment]
I am not connected to the Internet through a proxy server, so I can't test things. So, may I ask on which platform you are running OpenCOR? I believe I have a solution for you, but before committing it, I would like to make sure that it's working fine for you. So, my plan is to generate an 'ad hoc' version of OpenCOR for you to try and see how it goes. Let me know.

**Comment by tactmaster** [comment]
WIndows 7 and can you make sure it is a portable I don't have administrative privileges.
That would be great thank you.

**Comment by agarny** [comment]
Ok, here it is (note: we only ship 64-bit versions now, so I hope it's fine for you):
 - [Windows version of OpenCOR using the system's proxy settings](https://www.dropbox.com/s/bs7954426008y2z/2015-12-14-WITH-Proxy-Settings.zip?dl=0).
 - [Windows version of OpenCOR NOT using the system's proxy settings](https://www.dropbox.com/s/dnwp1ibaheh12e8/2015-12-14-WITHOUT-Proxy-Settings.zip?dl=0) (for control).

Let me know when you have tried them, so that I can remove them from my Dropbox account.

**Comment by tactmaster** [comment]
Some success. The model repository has a list of models. Instead of "Error: connection refused."
Check for update seems to be work again not saying connection refused
cellml models seem to be loading find as well
However then I try and download a model from the model repository I get this error

![image](https://cloud.githubusercontent.com/assets/793117/11807040/7b116b5c-a317-11e5-8511-5267c0ab4dbb.png)

Is it using a different protocol to get the file? (This could be a problem with the proxy config)

Just to note the proxy I am going though uses a .pac file to configure the proxy.

Thanks very much

**Comment by agarny** [comment]
> cellml models seem to be loading find as well

I take it that you are talking about loading a CellML file from within the "Physiome Model Repository" window? (Indeed, any local CellML file should open just fine, e.g. the models that are shipped with OpenCOR).

> However then I try and download a model from the model repository I get this error

May I ask whether this is happening for a workspace in particular or whether it happens for 'all' of the workspaces?

Otherwise, the error you got is a [Git](https://git-scm.com/)-related error. Indeed, the Physiome Model Repository relies on Git to keep track of files, etc. Hmm... not sure why this would cause problems though. Maybe @metatoaster (the person behind the Physiome Model Repository) can shed some lights on this? Tommy?

In the meantime, it seems like the 'fix' is a step in the right direction, so I am going to commit it.

**Comment by tactmaster** [comment]
"Physiome Model Repository" window?  Yes

It is for all models that I have tired. Yes it is a git problem. I tired getting the repo manually using tortoisegit. It needed proxy setting added too. The manual clone worked. The I tired it again in openOCR
![image](https://cloud.githubusercontent.com/assets/793117/11808475/0cf5a4c6-a321-11e5-88d8-0648ab8c4a1f.png)

I would you say have definitely added proxy to openOCR. The git stuff I can workround.

Thanks very much.

**Comment by agarny** [comment]
Oh, I think I have just got it. Git support within OpenCOR is done through a third-party library ([libgit2](https://libgit2.github.com/)) and not through [Qt](http://www.qt.io/) (which is the framework used to develop OpenCOR and which now relies on a user's proxy settings). Ok, I am going to check that out...

**Comment by tactmaster** [comment]
Yeap sounds about right. Looks like then both libgit2 and tortoisegit are taking settings from .gitconfig in the user's root folder.

**Comment by agarny** [comment]
Ok, so am I to understand that everything is now fine (since OpenCOR itself now uses a user's proxy settings) and that it's a user's responsibility to ensure that ```git``` is properly set up on their computer to work through a proxy server (which would make sense since OpenCOR cannot or, rather, shouldn't control that aspect of ```git```)?

**Comment by tactmaster** [comment]
Yeap that seems reasonable to me. Thanks

**Comment by agarny** [comment]
Addressed in commit 0238110ca5f53d81de2177c00a602ead0c5cafec, so closing.
