### ISSUE TITLE
Don't make the building/packaging of OpenCOR depend on the 'build' directory

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#850]
In order to separate builds for different platforms, each platform has its own build directory with names like `./ubuntu`. CMake happily accepts this and will compile and link OpenCOR. However at install time it goes looking for libraries underneath `./build`:
```
$ ninja install
[1/1] Install the project...
FAILED: cd /home/dave/mac/build/OpenCOR/ubuntu && /usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Up-to-date: /usr/local/bin/OpenCOR
CMake Error at cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/home/dave/mac/build/OpenCOR/build/lib/libQt5CLucene.so.5".


ninja: build stopped: subcommand failed.
```

**Comment by agarny** [comment]
Are you trying to do something like:

```
$ cd [OpenCOR]/ubuntu
$ cmake -G Ninja ..
...
$ ninja
...
$ ninja install
...
```

If so, then I would expect things to fail at the first ```ninja``` call, assuming your ```[OpenCOR]/build``` is empty. Indeed, one of the first things the OpenCOR build system needs is access to ```../build/versiondate.txt```, which reference is indeed hard-coded since it needs to be listed in one of OpenCOR's ```.qrc``` files (you can see a similar reference in ```[OpenCOR]/res/ui.qrc```).

So, to be able to build OpenCOR somewhere else than ```[OpenCOR]/build```, we would need to be able to 'dynamically' reference built/generated files from a ```.qrc``` file. I am not sure how this could be done and, in fact, whether it could be done at all.

Is it really a 'problem' for you to have several copies of the OpenCOR code base, so that you can build your different versions in ```[OpenCOR]/build```?

**Comment by dbrnz** [comment]
Yes, I'm trying to do exactly this. I usually run the built application directly from its build directory and everything just works fine. However doing so for Ubuntu gave me an empty frame (plugins not being found??) hence I tried the install step. I'll happily use ./build now I understand why.

CMake's `configure_file` command can be used to substitute variable values in a file -- why not have configuration variables in `res/ui.qrc.in` and use configure_file to create `${CMAKE_BINARY_DIR}/res/qrc.in`?

**Comment by agarny** [comment]
> CMake's ```configure_file``` command can be used to substitute variable values in a file -- why not have configuration variables in ```res/ui.qrc.in``` and use configure_file to create ```${CMAKE_BINARY_DIR}/res/qrc.in```?

Good point, that ought to work indeed. Ok, I will give that a try.

**Comment by agarny** [comment]
FWIW, it's effectively working fine (in the [```issue850``` branch](https://github.com/opencor/opencor/tree/issue850)). I just want to double check something in the various OpenCOR tests and I will then merge everything in to ```master```.
