### ISSUE TITLE
Have a URL scheme handler for OpenCOR

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#903]
OpenCOR plugins can send actions to OpenCOR using OpenCOR's URL protocol. For example, to open a file, a plugin would make a call similar to this (see issue #901 for more background on this):

```
QDesktopServices::openUrl("gui://openFile//home/user/file");
```

Now, it would be able to do something similar from one's web browser. Rather than the ```gui``` scheme, we would most likely use ```opencor```, but the point remains: to be able to interact with OpenCOR directly from one's web browser. Indeed, by having this, we could, in PMR, have a link to open a CellML/SED-ML file by having someone clicking on a link.

**Comment by dbrnz** [comment]
I would be cautious about arbitrary defining new URL schemes for use within an arbitrary web-browser as strictly speaking schemes need to be registered with IANA (see [RFC 7595](https://tools.ietf.org/html/rfc7595)). Or by "web-browser" do you mean a WebKit widget running within OpenCOR, with OpenCOR capturing mouse clicks?? In which case, fine.

In general, if a browser was running say JavaScript that interacted with a remote OpenCOR service, I recommend using the `http` protocol (not the same as the `http` scheme) as this simplifies firewall and proxy traversal, and then use content-negotiation when making requests to the service (e.g. an `Accept` header of  `application/opencor+json`).

**Comment by agarny** [comment]
> I would be cautious about arbitrary defining new URL schemes for use within an arbitrary web-browser as strictly speaking schemes need to be registered with IANA (see RFC 7595). Or by "web-browser" do you mean a WebKit widget running within OpenCOR, with OpenCOR capturing mouse clicks?? In which case, fine.

The latter has already been available in OpenCOR since version 0.1. For example, in the OpenCOR help, you have links like ```gui://openAboutDialogBox``` to open the About dialog box by clicking on a link in the help.

The idea is now to extend that concept to any web page, be it part of the OpenCOR help or not. In other words, we could, in PMR, have links like ```<a href="opencor://openFile/https://models.physiomeproject.org/w/andre/HH/rawfile/957c2190e1eed47d7634613250bc274dc836b826/experiments/periodic-stimulus.xml">Open remote CellML 1.1 HH model</a><``` which, when clicked, would start OpenCOR (if it's not yet running) and, in this particular case, open the the CellML 1.1 HH model that is on PMR. I have already got this working on OS X. I am currently cleaning things up and I am then going to get things to work on Windows (easy, apparently) and on Linux (according to @metatoaster, it looks like it might be possible using ```xdg-open```).

So, as far as you know/can tell, is that something that is fine to do?

**Comment by metatoaster** [comment]
While the registration process is a standard practice that ideally should be followed, by no means that process is absolutely required before this is used in common place (note the lack of bzr: in [the registry of current schemes](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) which bazaar (a version control system) typically use for their bzr+ssh:// checkout urls.

**Comment by dbrnz** [comment]
I urge caution about using the `scheme` component of a URL to mean "use OpenCOR to do something with the URL" because although OpenCOR aware services (e.g. PMR and the web-pages it serves) will know the meaning attached to the `opencor` scheme, general web applications will not. The URL might be embedded in an email or document (PDF, Word, ...); be part a RDF statement; show up in web search results; or whatever. What should various applications and users do when they come across these URLs??

Is it not better to use `http` URLs for web resources and then use content-negotiation to discover more about the resource and handle it accordingly? I can envisage a HTTP GET request (to PMR) with an `accept` header of `application/cellml+xml` and then receiving content of this type so the requester (JavaScript in the web-page) knows it has to invoke OpenCOR; a vanilla browser would request `text/html` and get back a human readable web-page; a RDF processor might request `text/turtle` or `application/ld+json` and receive metadata; etc.

This also enables other CellML aware applications to do their own thing with these URLs (in fact why does raw CellML served by PMR not always have a `content-type` of `application/cellml+xml` regardless? Currently it is `application/octet-stream`) and allows for semantically aware applications to discover more about the resource (by first requesting RDF) before deciding what best to do with the CellML referenced by the URL. This is all in keeping with [Linked Data](https://www.w3.org/TR/ldp-bp/) best practices.

**Comment by dbrnz** [comment]
Just a small quibble -- the title should be "Have a URL **scheme** handler for OpenCOR" since it is about URL schemes...

**Comment by metatoaster** [comment]
This have been already discussed extensively in the email threads that unfortunately were private, so I am going to redo all that work here.

> What should various applications and users do when they come across these URLs??

Ditto for URLs that start with `git://` or `ssh://` or heck even `irc://` by that line of thinking, don't you think?  So people using them must be cautious and use them only in context where they make sense, i.e. only within the context to communicate the need for launching OpenCOR.

> Is it not better to use http URLs for web resources and then use content-negotiation to discover more about the resource and handle it accordingly?

Yes, this is the default, however how do you propose telling the end-user web browser to launch a link to a resource file (i.e. CellML/SedML) within OpenCOR? If the answer is browser-based file type/mime type association, this is generally correct, but wrong in this case. Also, this has completely nothing to do with accept headers or whatever because those things are generally negotiated and have to be explicitly requested/understood by the client, and what we want to achieve is to pass a `http://` or `https://` resource directly from the web browser directly to a different application.

Generally file-type association handling done by **all** web browsers do is this: download the _singular_ target file onto the user's temporary directory and pass the `file:///` URL (or even just the path) of *that* new temporary file to the application associated with that mime-type, and then open. Now what happens to all the relative links that exist within that resource file? They become broken because those relatively linked references on the `http://` url isn't downloaded to the same relative temporary location, and there can be a huge number of them.

If your solution involves telling the server to package them (ala COMBINE Archive), it is not portable, and it isn't the same resource, also a LOT of extra work (CPU, programming time, also needing OpenCOR to understand COMBINE Archives) for those running servers.  If your solution is to tell the server to inject xml:base to the top-level file or otherwise manipulate all the relative links to absolute links, again you are wrong, because this changes the original resource and also end-users will end up passing those around and get persisted and then models break (we have this experience before).

A solution that still allow standard http links and get the web browser to launch OpenCOR with an explicit http(s) URL argument can be done using a surrogate launch script, but again this runs into the similar problem at a different level because users may click on that link, download that file and not be sure what that file does (even though it was properly labeled on the page that this link will *launch model using OpenCOR*, much like how this would have been labeled for the `opencor://` one), and then the http link will also be opaque to what it actually intends to do (launch OpenCOR and ONLY OpenCOR).  Also, the piece of text would probably only contain a thing that would launch OpenCOR, albeit served by the server using `application/vnd.opencor` but this mime type header will be lost once saved onto the user drive. Also, to communicate this across email will require usage of attachments.

In the end, why not just skip the proxies and directly use the URL scheme that is actually well-supported by the entire web community for this exact purpose, which is to explicitly state that this URL is proprietary to some application at hand.  It can be used _anywhere_ (say in a email client) without attachments or server-side support (for the mime-type), and the intent is well clearly stated out in textual form. Never mind that interoperability between the model repository and a dedicated desktop application is one of the funding objectives (at least back when PMR2 used to launch OpenCell, but this is superseded by OpenCOR and that objective hasn't changed) and one of the goals is to get the browser to launch this desktop application.

So @dbrnz, how do you propose communicating to the web browser that this `http://` link needs to be passed to OpenCOR instead outside of all the solution thave have been vetoed?

**Comment by nickerso** [comment]
I think the `opencor:` scheme is a great way to get started. If we start seeing `opencor://https://models.physiomeproject.org/w/andre/cool-model-version-3.xml` in the wild where they shouldn't be, then we can reevaluate and decide on an alternate approach. Or better communicate the purpose of these URLs.

**Comment by dbrnz** [comment]
I've obviously came into this without being part of the discussion @metatoaster summarised and now understand why, of the alternatives, using a URL scheme is the way forward.

What though is the resource identified by an `opencor:` URL? Is it just some class of objects used exclusively by OpenCOR? Or is it some class of objects held in PMR that other applications might also do things with? If the latter, would `pmr:` not be a better name for the scheme??

**Comment by nickerso** [comment]
> What though is the resource identified by an opencor: URL? Is it just some class of objects used exclusively by OpenCOR? Or is it some class of objects held in PMR that other applications might also do things with? If the latter, would pmr: not be a better name for the scheme??

As I understand it, OpenCOR itself will handle some resources specially (for tutorials, teaching, etc) and these are going to be exclusively for OpenCOR. As far as PMR is concerned, this is simply a mechanism by which the user is able to configure their browser to get a standard URL passed over to OpenCOR for loading, processing, executing, etc. The actual resource will be a normal http URL. I think :)
