### ISSUE TITLE
 Compiler engine: crashes OpenCOR on Linux due to an external function not being found by LLVM's execution engine

### ISSUE THREAD

**Issue by shouryadipta** [opencor/opencor#904]
Hi There,
          I recently developed a CellML model  using the Windows based OpenCOR, It runs all good there, but when I do the same in the Linux Version of OpenCOR, it crashes right after clicking the simulation tab. I've tried using different linux versions of OpenCOR, but the problem persists. Any help will be much appreciated. 

Shorjyo
RHD student
Uni Melb

**Comment by agarny** [comment]
Sorry Shorjyo, but with so little information, it's next to impossible to tell you what is going wrong with the Linux version of OpenCOR. A few questions, if you don't mind:
 - Which version of OpenCOR are you using on both Windows and Linux?
 - Are you able to run other CellML files on Linux or is that just with your model?
 - Is that a CellML 1.0 or 1.1 model? If the latter, I wonder whether the ```xlink:href``` attribute of ```import``` elements is not wrongly formatted (i.e. use ```\``` rather than ```/```), although I am not sure this would make OpenCOR crash.
 - Can you share the model that is causing you problems on Linux?

**Comment by shouryadipta** [comment]
Hi Alan, 
                   Thank you for your reply.

- I used the OpenCOR snapshot 2015-06-29 for the windows and OpenCOR Version 0.4.1 for the Linux OS. 

- Other CellML files run fine in both Windows and Linux

- It's 1.1 model, but there is no '\' present in the script. 

- On that note, would it be possible to share the file privately ? Kindly let me know.

**Comment by agarny** [comment]
Thanks Shorjyo.

> I used the OpenCOR snapshot 2015-06-29 for the windows and OpenCOR Version 0.4.1 for the Linux OS.

Not that it matters in your particular case since you are using the official version of OpenCOR on Linux, but if you want to use a snapshot on Windows then I would recommend using the latest one. The one you are currently using is rather old to say the least.

> Other CellML files run fine in both Windows and Linux

Ok, that's good to know.

> It's 1.1 model, but there is no '\' present in the script.

I would have been surprised if it had, but still worth checking.

> On that note, would it be possible to share the file privately ? Kindly let me know.

Of course. You can do that by emailing me at alan.garny@inria.fr. Make sure to include all the CellML files needed by your CellML 1.1 model.

Otherwise, may I ask which version of Linux you are using? FWIW, we are currently supporting Ubuntu 14.04 LTS (Trusty Tahr) and above.

**Comment by agarny** [comment]
Ok, Shorjyo, I can at least confirm your issue. I have just tried your model on Linux 14.04 LTS with both OpenCOR 0.4.1 and the latest snapshot available (2016-02-22), and though it works fine in ```Editing``` mode, it does indeed crash OpenCOR in ```Simulation``` mode. More on the reason and fix soon, I hope...

**Comment by shouryadipta** [comment]
Thanks so much Alan. Sorry about the mistake on cellml version. Looking
forward.....

**Comment by agarny** [comment]
Ok, the crash is due to the ```arbitrary_log``` function being needed by Shorjyo's model. Now, on Windows and OS X, it is all working fine, but on Linux, LLVM's execution engine can't find that function, resulting in OpenCOR crashing. So, we need to ensure that LLVM's execution engine knows about all the external functions that may be used by someone's model.

**Comment by agarny** [comment]
Shorjyo, as you can see, this issue has been fixed. Sorry again for the inconvenience! FWIW, I am hoping to generate a new snapshot sometime next week. So, you may want to use that on Linux, at least. (We have a mailing-list that is used to announce such releases; see http://localhost/user/contactUs.html)

**Comment by shouryadipta** [comment]
Hi Alan, Thanks so much. Looking forward to the new snapshot.
