### ISSUE TITLE
Single Cell view + SED-ML: boolean solver properties are not correctly retrieved from a SED-ML file

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#920]
I have an example where I can run a simulation from the CellML model and it runs fine, but if I use the SED-ML generated from that simulation the integration fails to complete. Setting a maximum step size in the SED-ML fixes the issue, but the difference in behaviour between the SED-ML and direct CellML model simulation is a bit puzzling (but not terribly urgent!).

* [model] (https://models.physiomeproject.org/workspace/25d/rawfile/31aa609fc5a976bb65b2803a4bc24776d4ef612b/sodium_ion_channel.cellml)
* [SED-ML without maximum step size set] (https://models.physiomeproject.org/workspace/25d/rawfile/46ffa273c788e9de16b17d8da5bc1cea2e6f4f9a/sodium_ion_channel.sedml)
* [SED-ML with the maximum step size set] (https://models.physiomeproject.org/workspace/25d/rawfile/31aa609fc5a976bb65b2803a4bc24776d4ef612b/sodium_ion_channel.sedml)

**Comment by agarny** [comment]
Never tell anyone that something is "not terribly urgent"! By doing that, some people might just think that you are giving them the go-ahead to ignore you! :)

Anyway, looking at the files you provided, I can see that there is a small problem in the current SED-ML import mechanism. Indeed, if you check CVODE's ```Interpolate solution``` parameter, you will see that its value is set to ```true``` for the two SED-ML files while it's set to ```True``` for the model file.

As a result, in the case of the SED-ML files, CVODE's ```Interpolate solution``` parameter is effectively set to ```False``` and this explains the difference of results you are getting (due to the protocol you are using).
