### ISSUE TITLE
PMR Interface as separate support plugin

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#931]
Currently PMR operations are part of the `PhysiomeModelRepositoryWindow` plugin. A new plugin (`PMRWorkspacesWindow`??) is being developed to allow users to manage their Workspaces as local clones and it seems sensible to create a new plugin (`PMRSupport`??) to provide PMR services common to the two Window plugins.

Issues #848 and #930 would belong to the new plugin.

**Comment by agarny** [comment]
Is the plan to have two windows, one specific to PMR and another for PMR workspaces? If so, I am wondering whether this is not going to overload the GUI? Couldn't we just have one 'big' window for PMR-related things?

If, for some reason or another, it cannot be done, then your suggestion makes sense to me, although I would stick to ```PhysiomeModelRepositoryXXX``` rather than ```PMRXXX```, mainly because in the window itself we probably want to use "Physiome Model Repository xxx" rather than "PMR xxx" since most people probably have no idea what PMR stands for.

**Comment by dbrnz** [comment]
I understand that the suggestion in the document at https://docs.google.com/document/d/16m12yxQxwI10EZPTRnNvXV4xcF54XFQqZz3a4LiujI0/edit#heading=h.tz52skwfb405 is to have a separate workspace window.

Hmm, what about a single big window but with two tabs, one for Exposures, the other for an authenticated user's Workspaces?? I do though like the idea having the possibility of cloning an exposure by dropping its icon (in the exposure window) onto the workspace window.

**Comment by agarny** [comment]
Unless I missed something, nothing is said about the current PMR window, so it's not clear to me whether the Workspaces window is to be merged with it or not. This being said, I like your idea of being able to dragging/dropping an exposure onto the workspace window. So, ok, let's go with that for now and see how it goes. In other words: I am fine with your proposal.
