### ISSUE TITLE
OpenCOR-2016-03-31 can't run on Win 10 Enterprise

### ISSUE THREAD

**Issue by mtcooling** [opencor/opencor#946]
Just tried OpenCOR-2016-03-31-Windows on Win 10 Enterprise. Installs OK, but when I try to run OpenCOR itself, it crashes. I tried both with and without admin privileges in case that made a difference. It didn't seem to.

I realise it's a dev snapshot but thought you might like to know anyway.

**Comment by agarny** [comment]
Hmm, it's working fine for me here on Windows 10 Home, but then again OpenCOR is currently built using Qt 5.4.2, which does not officially support Windows 10. So, maybe that's the reason it doesn't work on Windows 10 Enterprise?

Anyway, I am currently working on upgrading to Qt 5.6 (see issue #908), so hopefully it will make a difference. Wait and see, I guess.

**Comment by agarny** [comment]
From an email exchange, it looks like a 'special' snapshot can be run on Windows 10 Enterprise. So, it might be that the 2016-03-31 snapshot had something 'funny' that prevented it from working as expected on Windows 10 Enterprise? Whatever the case, we are closing this issue since everything seems to be fine (and should, hopefully, still be fine with the forthcoming snapshot).
