### ISSUE TITLE
Conflicting names of HTML resource files

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#978]
The resource `./src/plugins/organisation/PMRWindow/res/output.html` is referred to as `/:output.html` within its plugin. The resource name is apparently in the global namespace, since if there is a `./src/plugins/organisation/PMRWorkspaces/res/output.html`, also referred to as `/:output.html`, it is the first instance of `:/output.html` that gets opened, regardless of the plugin referencing the resource.

A solution is to rename the respective files to `pmrwindowwidget.html` and `pmrworkspaceswidget.html` to reflect their use.

**Comment by agarny** [comment]
Good catch!

Now, your solution clearly works, but I am wondering whether we couldn't come with a generic solution instead?

If we think of the `PMRWindow` plugin, we used to have one HTML file: `[PMRWindow]/res/output.html`, which you renamed `[PMRWindow]/res/pmrwindowwidget.html`. However, a generic solution could be to have `[PMRWindow]/res/pmrwindow/output.html`. What do you think? If you agree, I am then happy to do that kind of change for all our plugins.

**Comment by dbrnz** [comment]
I was thinking of the possibility that a plugin may have more than one HTML template, hence renaming from the generic use of `output.html`.

We do need a general solution though as other resources with common names amongst the different plugins  (e.g. png files) are in the global namespace (I've just tried modifying a png file for one plugin and yes, it applies globally...), so let's go with having all of a plugin's resources under `[PLUGIN]/res/plugin/`. A core set of png icon files could though be under the top level `./res/` directory, and described in `./res/ui.qrc`, which would minimise changes to the source files that reference them (e.g. `:/oxygen/actions/list-add.png` would stay unchanged) -- I've just tried this with one file and all is fine.

**Comment by dbrnz** [comment]
Another general solution would be to leave the resource directories as they are and instead have a prefix of `/plugin_name` for <qresource> elements. Each reference to a resource file would then need `/plugin_name` added as a prefix.

If common icons were to kept in a global directory would it not be sensible to use aliases? e.g.
```
        <file alias="actions/list-add.png">oxygen/actions/list-add.png</file>
```
This would allow icon themes to be updated without having to change all references to each icon file.

**Comment by agarny** [comment]
> I was thinking of the possibility that a plugin may have more than one HTML template, hence renaming from the generic use of `output.html`.

Sure, although it isn't the case with the current PMR window plugin, hence `output.html`.

> We do need a general solution though as other resources with common names amongst the different plugins  (e.g. png files) are in the global namespace (I've just tried modifying a png file for one plugin and yes, it applies globally...), so let's go with having all of a plugin's resources under `[PLUGIN]/res/plugin/`. A core set of png icon files could though be under the top level `./res/` directory, and described in `./res/ui.qrc`, which would minimise changes to the source files that reference them (e.g. `:/oxygen/actions/list-add.png` would stay unchanged) -- I've just tried this with one file and all is fine.

Yes and as you probably noticed, most of those png files come from the [Oxygen library](http://packages.ubuntu.com/yakkety/oxygen-icon-theme). I agree that it would be nice to have them centrally located and to have them under `[OpenCOR]/res/oxygen` would indeed make sense (in fact, there are already some of them there). The reason I hadn't done it yet is that the library is somewhat big. However, I have just checked and it is indeed big in term of the number of images it contains (1,223 images apparently), but not so big in terms of physical size ('only' 3.52 MB apparently), so I think I am going to put the whole contents of the Oxygen library in there, so that any plugin can refer to any of those Oxygen images without any problem (see issue #982).

> Another general solution would be to leave the resource directories as they are and instead have a prefix of `/plugin_name` for <qresource> elements. Each reference to a resource file would then need `/plugin_name` added as a prefix.

Hmm, I had seen that 'prefix' attribute, but had never thought of using it before. Well, it looks like it might indeed be what we should do rather than putting resources in `[Plugin]/res/plugin` (see updated issue #981).

> If common icons were to kept in a global directory would it not be sensible to use aliases? e.g.
> ```
>         <file alias="actions/list-add.png">oxygen/actions/list-add.png</file>
> ```
> This would allow icon themes to be updated without having to change all references to each icon file.

Are you concerned about the fact that, in the future, `actions/list-add.png` may not be under the `oxygen` directory anymore? If so, then I guess the same could be said about the filename of an image. I mean, if we were ever to change libraries, then some images may end up with a different filename or even be dropped. So, right now, I feel like leaving things as-is, but we can reconsider this issue at some other point, if needed.

So, at this point, I think we have come up with issues #981 and #982, which I am going to implement.

**Comment by agarny** [comment]
Issues #981 and #982 have now been implemented, so re-closing this issue.

**Comment by dbrnz** [comment]
>>    If common icons were to kept in a global directory would it not be sensible to use aliases? e.g.
>>
>>           <file alias="actions/list-add.png">oxygen/actions/list-add.png</file>
>>
>>   This would allow icon themes to be updated without having to change all references to each icon file.

> Are you concerned about the fact that, in the future, actions/list-add.png may not be under the oxygen directory anymore? If so, then I guess the same could be said about the filename of an image. I mean, if we were ever to change libraries, then some images may end up with a different filename or even be dropped. So, right now, I feel like leaving things as-is, but we can reconsider this issue at some other point, if needed.

I see using aliases as a way to separate the visual meaning if an icon (the "Add" action) from the name of the file that holds the image used for the icon (i.e. the icon's implementation). As you say, something that can be reconsidered later.
