### ISSUE TITLE
CellML Text view: allow the user to save the contents of the view to a text file if it cannot be saved as a CellML file

### ISSUE THREAD

**Issue by gbernardino** [opencor/opencor#998]
It would be nice to allow users to save the editing even when the cellML text has some mistakes and can not be transformed to raw CellML.

**Comment by agarny** [comment]
I was hoping that being able to comment something out would be good enough, but clearly not. @gbernardino, may I ask you for a concrete example of where such a feature would be useful to you?

Otherwise, and assuming that such a feature is indeed deemed necessary, I have yet to come across a 'proper' way of implementing it. What is certain is that I am not in favour of keeping track of such a malformed CellML Text code in a CellML file. Also, if such a feature was to be implemented, this would brings another level of complexity. Indeed, we have to keep in mind that upon 'successfully' saving a file, OpenCOR lets the other views that a file has been saved, thus allowing those views to update themselves, etc.

So, maybe that rather than 'saving' as such, maybe we could have a mechanism by which we keep a 'snapshot' of the CellML Text view? The user could then be able to save several snapshots and retrieve whichever one he wants, and this at any point in time? This, however, would most likely require saving those snapshots in the CellML file itself... I might be convinced by that approach though...

**Comment by gbernardino** [comment]
Maybe it is not an issue for advanced users, but beginners struggle to write correct cellml code. If they want to save often, it is the case that not always the content of the file can generate the xml code. Of course, one option would be to comment everything, or save it manually in a text file whenever you want to save, but that is a bit annoying. I was hoping to find a better solution

I was thinking in saving the content of the CellML Text View in an extra file, but  as you said this can bring a lot of problems for a not so important thing.

**Comment by mirams** [comment]
Yeah, I'm not keen on malformed CellML files kicking around. Perhaps when you try to save it could say "This isn't valid CellML, so can't be saved as a .cellml file. Do you want to save the current view as a .txt file?"

**Comment by agarny** [comment]
Note that in my proposal, the malformed contents of the `CellML Text` view would be saved in the CellML file itself. It would just be saved as some kind of annotation that is specific to OpenCOR's `CellML Text` view. So, other CellML software would just 'ignore' it. This being said, this could potentially and unnecessarily blow up the size of a CellML, which wouldn't be great at all.

> Yeah, I'm not keen on malformed CellML files kicking around. Perhaps when you try to save it could say "This isn't valid CellML, so can't be saved as a .cellml file. Do you want to save the current view as a .txt file?"

This might actually be a nice workaround and this wouldn't break OpenCOR's workflow (although the user would still have to make the contents of the `CellML Text` view valid before actually being able to save a CellML file). @gbernardino, would @mirams' suggestion work for you?

**Comment by gbernardino** [comment]
@agarny,  what you propose covers perfectly the problem. 

I would not worry that much about storage space, as it is almost free nowadays. As long as at most only one Text View is saved at a time, it should be OK. The XML format is far from optimal in terms of used space, and it is not really a problem.

**Comment by agarny** [comment]
@gbernardino, besides the issue of storage, there is also that of 'clean' vs. 'unclean' CellML file, and my suggestion would result in an 'unclean' CellML file, which is definitely not nice. This is why I would like to know whether @mirams' suggestion would work for you.

**Comment by gbernardino** [comment]
@agarny  @mirams  if I have understood it correctly what you propose is making OpenCOR able to read and write .txt files. This works perfect for me.

Maybe in the future I would like also to be able to generate automatically cellml files. It is easier if I can do it with text instead of xml, so if OpenCOR is able to read text files, instead of copy-paste in the view it would be better.

**Comment by agarny** [comment]
> @agarny  @mirams  if I have understood it correctly what you propose is making OpenCOR able to read and write .txt files. This works perfect for me.

Sorry for the misunderstanding, but OpenCOR will never directly understand the CellML Text format, even though we now have a way to convert CellML to the CellML Text format and back (see issue #992).

The way I understood @mirams' suggestion is just that if you try, using the `CellML Text` view, to save a malformed CellML file then the view will tell you that it cannot do that (since the contents of the view is not valid), but that it can (for your convenience) save it as a text file. The idea being that you can, at a later stage, copy/paste the contents of that text file into the `CellML Text` view, if needed.

> Maybe in the future I would like also to be able to generate automatically cellml files. It is easier if I can do it with text instead of xml, so if OpenCOR is able to read text files, instead of copy-paste in the view it would be better.

I guess that the issue #992 that I mentioned above might already cover your needs (partially at least).

**Comment by gbernardino** [comment]
Maybe issue #992 also helps to save the text.  What should OpenCOR do when it tries to convert a file in CellML text to CellML and it is not a correct file? Maybe it is a clean way to proceed (save the file as CellML text instead of XML).

**Comment by agarny** [comment]
@gbernardino, if you use issue #992 to convert a CellML file to CellML Text file (or the reverse) and that the CellML file (or CellML Text file in the reverse case) is invalid, then OpenCOR will just tell you that the file is invalid and it will list whatever errors it found in it.

As for saving a model using the CellML Text format as opposed to pure CellML, this will simply never happen. Remember that the CellML Text format is only for convenience, nothing more nothing less, not to mention that it's not an easily portable format while CellML is (since it's an XML-based format).

**Comment by gbernardino** [comment]
Then I guess that the best way is to allow to save the view to a text file when there are errors.

**Comment by agarny** [comment]
Thanks @gbernardino, I will then implement it that way.
